"""One-shot backfill for the companies that predate the universe ingest:
adopt them into the ISIN-keyed model, correct broken tickers, merge the
spurious no-ISIN duplicate rows that resulted from them, and flag any
company that no longer exists on an exchange.

Run AFTER a snapshot exists:
    python -c "from datetime import date; from app.companies.universe import fetchers; \\
        fetchers.fetch_nse_equity_list('data/universe', date.today()); \\
        fetchers.fetch_bse_scrip_list('data/universe', date.today())"
    python backfill_universe.py

Verified against the live NSE master on 2026-08-03: HPCL and OILINDIA are
not NSE symbols (the real ones are HINDPETRO and OIL) and JBCHEPHARM is
absent from the master entirely.

AMENDED 2026-08-03: HPCL.NS and OILINDIA.NS turned out not to be mis-typed
tickers on the real companies -- they are spurious duplicate Company rows
with no ISIN, sitting alongside the correct HINDPETRO.NS/OIL.NS rows and
holding real alert history (Task 11's regression corpus surfaced this).
apply_ticker_corrections correctly SKIPS both renames (the target ticker
already exists); merge_duplicate_companies is what actually resolves them,
by folding the phantom into the canonical company and deleting it.
"""
import argparse
import contextlib

from sqlalchemy import bindparam, event, text
from sqlalchemy.orm import Session

from app.companies.global_seed import GLOBAL_COMPANIES
from app.companies.matching import aliases
from app.companies.universe import loader, normalize, snapshot
from app.db import SessionLocal, engine as _default_engine
from app.models import Company

TICKER_CORRECTIONS = {
    "HPCL.NS": "HINDPETRO.NS",
    "OILINDIA.NS": "OIL.NS",
}


def apply_ticker_corrections(session: Session) -> list[tuple[str, str]]:
    """Rewrite known-wrong tickers in place. companies.id is untouched, so
    every alert_companies row and the whole price/outcome history survives.

    A correction whose target ticker already exists is SKIPPED rather than
    merged -- merging two companies means reassigning FK rows, which is a
    separate, deliberate operation. In this database BOTH corrections hit
    that path (see merge_duplicate_companies, which handles them).
    """
    changed = []
    for wrong, right in TICKER_CORRECTIONS.items():
        company = session.query(Company).filter_by(ticker=wrong).one_or_none()
        if company is None:
            continue
        if session.query(Company).filter_by(ticker=right).count():
            print(f"SKIP {wrong} -> {right}: target already exists, needs a manual merge")
            continue
        company.ticker = right
        changed.append((wrong, right))
    session.commit()
    return changed


def flag_missing_tickers(session: Session, known_symbols: set[str]) -> list[str]:
    """Mark Indian companies whose symbol is absent from the exchange master
    as SUSPENDED. Never deletes: a company that has left the exchange is
    still a real company with a real ISIN (JBCHEPHARM.NS, INE572A01036, is
    the live example -- it has zero alert history, so that is NOT why it
    survives), and a delisting is a fact to record, not a reason to erase
    the past. Deleting is reserved for the phantom no-ISIN duplicates that
    merge_duplicate_companies handles.
    """
    flagged = []
    for company in session.query(Company).filter(Company.market == "INDIA").all():
        symbol = company.ticker.rsplit(".", 1)[0]
        if symbol in known_symbols:
            continue
        company.tradeability = "SUSPENDED"
        flagged.append(company.ticker)
    session.commit()
    return flagged


DUPLICATE_MERGES = [
    # (phantom ticker, canonical ticker). Both phantoms were created without
    # an ISIN and duplicate a real company that has one.
    ("HPCL.NS", "HINDPETRO.NS"),
    ("OILINDIA.NS", "OIL.NS"),
]

# Derivable rows: regenerated by rebuild_aliases / the ingest, so the
# phantom's copies are deleted rather than reassigned (reassigning would
# collide with the canonical company's own rows on their unique keys).
_DERIVABLE_TABLES = ("company_aliases", "listings", "company_index_memberships")

# History rows: irreplaceable, so these are REASSIGNED to the canonical id.
# (table, column) for every remaining FK onto companies.id.
_HISTORY_FKS = (
    ("alert_companies", "company_id"),
    ("alert_companies", "parent_company_id"),
    ("impact_edges", "from_company_id"),
    ("impact_edges", "to_company_id"),
    ("calibration_samples", "company_id"),
    ("car_outcomes", "company_id"),
    ("market_moves", "company_id"),
    ("holdings", "company_id"),
    ("user_watchlist_companies", "company_id"),
)

# (table, company column) -> the other column of that table's unique
# constraint that also covers company_id:
#   market_moves               uq_market_move_alert_company (alert_id, company_id)
#   user_watchlist_companies   uq_watchlist_company_user_company (user_id, company_id)
# A blind bulk UPDATE of company_id on these tables can violate that
# constraint (e.g. the same user already watches the canonical company).
# Rows whose sibling value the canonical already owns are deleted instead
# of reassigned -- the fact is already recorded against the canonical
# company -- and only the non-colliding rows are moved.
#
# `holdings` ALSO has such a constraint (uq_holdings_user_company, on
# user_id + company_id) but is deliberately NOT listed here: a Holding
# carries `quantity` (and implicitly cost basis), so a colliding pair is a
# financial-data reconciliation decision, not a duplicate to discard. See
# _holdings_collision -- a collision there refuses the whole merge instead.
#
# The remaining _HISTORY_FKS tables have no such constraint (alert_companies,
# impact_edges) or one that doesn't involve company_id (calibration_samples,
# car_outcomes), so a plain bulk UPDATE is safe for them.
_HISTORY_SIBLING_KEY = {
    ("market_moves", "company_id"): "alert_id",
    ("user_watchlist_companies", "company_id"): "user_id",
}


def _sibling_keys(session: Session, table: str, column: str, sibling: str, id_: int) -> set:
    return {
        row[0] for row in session.execute(
            text(f"SELECT {sibling} FROM {table} WHERE {column} = :id"), {"id": id_},
        )
    }


def _holdings_collision(session: Session, phantom_id: int, canonical_id: int) -> bool:
    """True if the phantom and the canonical both carry a Holding for the
    same user. Checked before any write for a pair -- see the docstring of
    merge_duplicate_companies for why this refuses the whole merge rather
    than reconciling."""
    canonical_users = _sibling_keys(session, "holdings", "company_id", "user_id", canonical_id)
    if not canonical_users:
        return False
    phantom_users = _sibling_keys(session, "holdings", "company_id", "user_id", phantom_id)
    return bool(canonical_users & phantom_users)


def _reassign_with_collision_guard(
    session: Session, table: str, column: str, sibling: str, phantom_id: int, canonical_id: int,
) -> dict[str, int]:
    counts: dict[str, int] = {}
    canonical_keys = _sibling_keys(session, table, column, sibling, canonical_id)
    phantom_rows = session.execute(
        text(f"SELECT id, {sibling} FROM {table} WHERE {column} = :pid"), {"pid": phantom_id},
    ).all()

    colliding_ids = [row[0] for row in phantom_rows if row[1] in canonical_keys]
    movable_ids = [row[0] for row in phantom_rows if row[1] not in canonical_keys]

    if colliding_ids:
        stmt = text(f"DELETE FROM {table} WHERE id IN :ids").bindparams(
            bindparam("ids", expanding=True)
        )
        session.execute(stmt, {"ids": colliding_ids})
        counts[f"{table}.{column} (deleted duplicate)"] = len(colliding_ids)

    if movable_ids:
        stmt = text(f"UPDATE {table} SET {column} = :cid WHERE id IN :ids").bindparams(
            bindparam("ids", expanding=True)
        )
        session.execute(stmt, {"cid": canonical_id, "ids": movable_ids})
        counts[f"{table}.{column}"] = len(movable_ids)

    return counts


def merge_duplicate_companies(session: Session, pairs=DUPLICATE_MERGES) -> list[dict]:
    """Fold a phantom duplicate company into the real one and delete it.

    Task 11's regression corpus proved these exist: HPCL.NS (no ISIN, 2
    alerts) shadowing HINDPETRO.NS (INE094A01015, 5 alerts), and
    OILINDIA.NS (no ISIN, 1 alert) shadowing OIL.NS (INE274J01014). The
    phantoms will never appear in an exchange master, so without a merge
    their alert history is stranded on rows that can never be enriched,
    ranked, or priced.

    SAFETY RULE, enforced not assumed: a merge only proceeds when the
    phantom has NO ISIN and the canonical HAS one. Anything else is
    reported and skipped -- this function must never be able to delete a
    real company.

    Derivable rows (aliases, listings, index memberships) are deleted
    because the canonical company already has its own and they regenerate.
    History rows are reassigned. A history row that would violate a unique
    constraint after reassignment is deleted instead, and counted, so the
    merge cannot fail partway and strand the rest -- EXCEPT `holdings`,
    where a collision is a financial-data reconciliation call (a Holding
    carries quantity/cost basis) this script has no business making: that
    check runs before any write for the pair, and a collision refuses the
    whole merge, leaving both companies and both holdings untouched.
    """
    report = []
    for phantom_ticker, canonical_ticker in pairs:
        phantom = session.query(Company).filter_by(ticker=phantom_ticker).one_or_none()
        canonical = session.query(Company).filter_by(ticker=canonical_ticker).one_or_none()
        if phantom is None or canonical is None:
            report.append({"phantom": phantom_ticker, "skipped": "not found"})
            continue
        if phantom.isin:
            report.append({"phantom": phantom_ticker, "skipped": "phantom has an ISIN -- not a phantom"})
            continue
        if not canonical.isin:
            report.append({"phantom": phantom_ticker, "skipped": "canonical has no ISIN -- cannot confirm identity"})
            continue

        # Capture ids up front: used after `phantom` is deleted below.
        phantom_id, canonical_id = phantom.id, canonical.id

        # Refuse the whole pair BEFORE any write if holdings collide --
        # unlike market_moves/user_watchlist_companies, a Holding is user
        # financial data (quantity, and implicitly cost basis). Deleting
        # one silently destroys a position; summing is a decision this
        # script must not make unasked. Checked first so nothing is
        # half-applied for this pair.
        if _holdings_collision(session, phantom_id, canonical_id):
            report.append({
                "phantom": phantom_ticker, "canonical": canonical_ticker,
                "skipped": "holdings collision -- needs manual reconciliation",
            })
            continue

        moved: dict[str, int] = {}
        for table in _DERIVABLE_TABLES:
            result = session.execute(
                text(f"DELETE FROM {table} WHERE company_id = :pid"), {"pid": phantom_id},
            )
            if result.rowcount:
                moved[f"{table} (deleted)"] = result.rowcount

        for table, column in _HISTORY_FKS:
            sibling = _HISTORY_SIBLING_KEY.get((table, column))
            if sibling is None:
                result = session.execute(
                    text(f"UPDATE {table} SET {column} = :cid WHERE {column} = :pid"),
                    {"cid": canonical_id, "pid": phantom_id},
                )
                if result.rowcount:
                    moved[f"{table}.{column}"] = result.rowcount
                continue

            moved.update(
                _reassign_with_collision_guard(session, table, column, sibling, phantom_id, canonical_id)
            )

        # The derivable-table DELETEs above already removed `phantom`'s
        # company_aliases/listings rows via raw SQL, bypassing the ORM. If
        # either relationship collection is still loaded on `phantom` (e.g.
        # a caller touched `.aliases`/`.listings`, or rebuild_aliases ran
        # earlier in this session), SQLAlchemy's default nullify-on-delete
        # cascade would try to UPDATE those now-gone child rows when
        # `phantom` is deleted, match 0 rows, and raise StaleDataError ->
        # PendingRollbackError -- the exact "fail partway" this function
        # promises cannot happen. Expiring first forces a fresh (empty)
        # reload of both collections, so the cascade has nothing to do.
        session.expire(phantom, ["aliases", "listings"])
        session.delete(phantom)
        session.commit()
        report.append({
            "phantom": phantom_ticker, "canonical": canonical_ticker,
            "phantom_id": phantom_id, "canonical_id": canonical_id, "moved": moved,
        })
    return report


def mark_global_companies(session: Session) -> int:
    """Set market='GLOBAL' on the curated non-Indian list. These rows have
    no ISIN, no listings, and never receive a cap tier -- AMFI ranking is
    India-only and inventing a global scale would be exactly the kind of
    unsourced number this design rejects."""
    global_tickers = {entry["ticker"] for entry in GLOBAL_COMPANIES}
    marked = 0
    for company in session.query(Company).filter(Company.ticker.in_(global_tickers)).all():
        if company.market != "GLOBAL":
            company.market = "GLOBAL"
            marked += 1
    session.commit()
    return marked


def validate_isin_invariant(session: Session) -> list[str]:
    """Every market='INDIA' company must carry an ISIN.

    Spec §5.1 called for a CHECK constraint. SQLite cannot add one via
    ALTER TABLE (there is no Alembic in this project -- see app/db.py), so
    the invariant is enforced here and asserted in the test suite instead.
    Returns the offending tickers; an empty list means the universe is
    clean.
    """
    return [
        ticker for ticker, in session.query(Company.ticker)
        .filter(Company.market == "INDIA")
        .filter((Company.isin.is_(None)) | (Company.isin == ""))
        .all()
    ]


def _apply(session: Session, nse_rows: list[dict], bse_rows: list[dict], details: dict, day) -> dict:
    """The actual backfill pipeline, shared verbatim by a real run and a
    --dry-run: dry-run's honesty depends on running the EXACT SAME code
    path (not a hand-maintained parallel "preview" implementation that
    could silently drift from what a real run does), with only the
    enclosing transaction's fate differing (see run() / _dry_run_session).
    """
    corrections = apply_ticker_corrections(session)
    print("corrections:", corrections)
    globals_marked = mark_global_companies(session)
    print("globals marked:", globals_marked)
    # Runs AFTER corrections (which will skip both, since the canonical
    # tickers already exist) and BEFORE the upsert, so the phantom rows
    # are gone before aliases are rebuilt for them.
    merges = merge_duplicate_companies(session)
    for entry in merges:
        print("merge:", entry)

    records = normalize.build_records(nse_rows, bse_rows, details, day)
    existing_tickers = {
        ticker for ticker, in
        session.query(Company.ticker).filter(Company.market == "INDIA").all()
    }
    # Backfill ONLY the companies already present. The full ingest is a
    # separate, later step (ingest_universe.py) so this run can never
    # grow the universe by accident.
    scoped = [r for r in records if r["ticker"] in existing_tickers]
    upsert_result = loader.upsert_records(session, scoped)
    print("upsert:", upsert_result)

    known = {r["SYMBOL"] for r in nse_rows} | {
        (r.get("scrip_id") or "").strip() for r in bse_rows
    }
    flagged = flag_missing_tickers(session, known)
    print("flagged missing:", flagged)
    alias_result = aliases.rebuild_aliases(session)
    print("aliases:", alias_result)

    offenders = validate_isin_invariant(session)
    if offenders:
        print(f"WARNING: {len(offenders)} Indian companies still lack an ISIN: {offenders[:10]}")

    return {
        "corrections": corrections,
        "globals_marked": globals_marked,
        "merges": merges,
        "upsert": upsert_result,
        "flagged_missing": flagged,
        "aliases": alias_result,
        "isin_offenders": offenders,
    }


_sqlite_savepoint_patched: set[int] = set()


def _ensure_sqlite_savepoint_support(bind_engine) -> None:
    """SQLite's pysqlite DBAPI driver runs its own implicit
    BEGIN/COMMIT underneath SQLAlchemy's transaction management, which
    silently lets writes escape an outer, externally-controlled
    transaction's rollback -- confirmed empirically: without this, a bare
    connection.begin() + session.begin_nested() + rollback() on an
    unmodified SQLite engine still PERSISTS everything written inside.
    Standard SQLAlchemy workaround: disable pysqlite's own transaction
    handling (isolation_level = None) and issue BEGIN ourselves. PostgreSQL
    (production, via psycopg2) needs no such workaround and this is a
    no-op for it. Applied once per engine.
    """
    if bind_engine.dialect.name != "sqlite" or id(bind_engine) in _sqlite_savepoint_patched:
        return
    _sqlite_savepoint_patched.add(id(bind_engine))

    @event.listens_for(bind_engine, "connect")
    def _do_connect(dbapi_connection, connection_record):
        dbapi_connection.isolation_level = None

    @event.listens_for(bind_engine, "begin")
    def _do_begin(conn):
        conn.exec_driver_sql("BEGIN")


@contextlib.contextmanager
def _dry_run_session(bind_engine):
    """Yield a Session whose writes CANNOT reach the database, regardless
    of how many times code running inside it calls session.commit() --
    every helper this module's pipeline calls (apply_ticker_corrections,
    mark_global_companies, merge_duplicate_companies, upsert_records,
    flag_missing_tickers, rebuild_aliases) commits internally, and --dry-run
    must run that exact same code (see _apply's docstring) while writing
    nothing.

    This is SQLAlchemy's documented "join a Session to an external
    transaction" recipe: bind the Session to a Connection that owns its own
    transaction, open a SAVEPOINT, and re-open a fresh SAVEPOINT every time
    the Session's own commit() releases the current one (via the
    after_transaction_end hook). session.commit() then only ever
    releases/reopens the SAVEPOINT; the outer Connection-level transaction
    -- which is what actually persists anything to disk -- is rolled back
    unconditionally on exit, real exception or not.
    """
    _ensure_sqlite_savepoint_support(bind_engine)
    connection = bind_engine.connect()
    outer_transaction = connection.begin()
    session = Session(bind=connection)
    session.begin_nested()

    @event.listens_for(session, "after_transaction_end")
    def _restart_savepoint(session_, transaction):
        if transaction.nested and not transaction._parent.nested:
            session_.begin_nested()

    try:
        yield session
    finally:
        session.close()
        outer_transaction.rollback()
        connection.close()


def run(root: str | None = None, day=None, dry_run: bool = False, engine=None) -> dict:
    """Load the latest (or given) snapshot and run the full backfill
    pipeline against it. ``engine`` defaults to the app's real database
    engine; overridable for tests. When ``dry_run`` is True, every helper
    below still runs -- and prints/returns the exact same report a real run
    would -- but nothing is written (see _dry_run_session)."""
    root = root or snapshot.DEFAULT_ROOT
    bind_engine = engine or _default_engine
    if day is None:
        day = snapshot.latest_snapshot_day(root)
    if day is None:
        raise SystemExit(f"no snapshot found under {root}; fetch the masters first")

    nse_rows = normalize.parse_nse_rows(
        snapshot.master_path(root, day, "nse_equity_l.csv").read_text(encoding="utf-8")
    )
    bse_rows = normalize.parse_bse_rows(
        snapshot.master_path(root, day, "bse_scrips.json").read_text(encoding="utf-8")
    )
    details = {
        p.stem: normalize.parse_bse_detail(p.read_text(encoding="utf-8"))
        for p in (snapshot.snapshot_dir(root, day) / snapshot.DETAIL_DIRNAME).glob("*.json")
    }

    if dry_run:
        print("DRY RUN -- reporting every would-be change, writing nothing")
        with _dry_run_session(bind_engine) as session:
            result = _apply(session, nse_rows, bse_rows, details, day)
        print("DRY RUN complete -- nothing was written")
        return result

    session = SessionLocal() if engine is None else Session(bind=bind_engine)
    try:
        return _apply(session, nse_rows, bse_rows, details, day)
    finally:
        session.close()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--dry-run", action="store_true",
        help=(
            "print every correction, merge (with its per-table FK row "
            "counts), global mark, and flagged-suspended company that "
            "WOULD happen, and write nothing"
        ),
    )
    args = parser.parse_args()
    run(dry_run=args.dry_run)


if __name__ == "__main__":
    main()
