"""baseline

Revision ID: 0001
Revises: 
Create Date: 2026-08-13 11:59:22.042769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('output_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash', name='uq_analysis_cache_content_hash')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('full_content', sa.Text(), nullable=True),
    sa.Column('full_content_fetch_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('provider_article_id', sa.String(), nullable=True),
    sa.Column('url_hash', sa.String(), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('source_category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', name='uq_articles_url')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index('ix_articles_provider_article_id', ['provider', 'provider_article_id'], unique=False)
        batch_op.create_index('ix_articles_url_hash', ['url_hash'], unique=False)

    op.create_table('category_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('lang', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'lang', name='uq_category_translation_lang')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('sub_sector', sa.String(), nullable=True),
    sa.Column('index_tier', sa.String(), nullable=False),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('instrument_token', sa.Integer(), nullable=True),
    sa.Column('business_desc', sa.Text(), nullable=True),
    sa.Column('business_desc_source_url', sa.String(), nullable=True),
    sa.Column('business_desc_as_of', sa.Date(), nullable=True),
    sa.Column('supply_chain_suppliers_json', sa.Text(), nullable=True),
    sa.Column('supply_chain_customers_json', sa.Text(), nullable=True),
    sa.Column('market', sa.String(), server_default='INDIA', nullable=False),
    sa.Column('official_sector', sa.String(), nullable=True),
    sa.Column('official_industry', sa.String(), nullable=True),
    sa.Column('official_igroup', sa.String(), nullable=True),
    sa.Column('official_isubgroup', sa.String(), nullable=True),
    sa.Column('classification_source', sa.String(), nullable=True),
    sa.Column('classification_as_of', sa.Date(), nullable=True),
    sa.Column('market_cap_source', sa.String(), nullable=True),
    sa.Column('market_cap_as_of', sa.Date(), nullable=True),
    sa.Column('shares_outstanding', sa.Float(), nullable=True),
    sa.Column('shares_outstanding_as_of', sa.Date(), nullable=True),
    sa.Column('amfi_tier', sa.String(), nullable=True),
    sa.Column('amfi_rank', sa.Integer(), nullable=True),
    sa.Column('amfi_as_of', sa.Date(), nullable=True),
    sa.Column('tradeability', sa.String(), server_default='NORMAL', nullable=False),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('ceps', sa.Float(), nullable=True),
    sa.Column('pe', sa.Float(), nullable=True),
    sa.Column('pb', sa.Float(), nullable=True),
    sa.Column('opm', sa.Float(), nullable=True),
    sa.Column('npm', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('con_eps', sa.Float(), nullable=True),
    sa.Column('con_ceps', sa.Float(), nullable=True),
    sa.Column('con_pe', sa.Float(), nullable=True),
    sa.Column('con_pb', sa.Float(), nullable=True),
    sa.Column('con_opm', sa.Float(), nullable=True),
    sa.Column('con_npm', sa.Float(), nullable=True),
    sa.Column('con_roe', sa.Float(), nullable=True),
    sa.Column('financials_source', sa.String(), nullable=True),
    sa.Column('financials_as_of', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('financial_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('return_1m', sa.Float(), nullable=True),
    sa.Column('return_3m', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', name='uq_financial_snapshot_ticker')
    )
    op.create_table('ingestion_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('poll_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('cursor', sa.Text(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_fetched_count', sa.Integer(), nullable=True),
    sa.Column('last_inserted_count', sa.Integer(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('breaker_open_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avg_publish_to_fetch_latency_seconds', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('llm_call_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('call_name', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('thinking_level', sa.String(), nullable=True),
    sa.Column('thinking_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Integer(), nullable=True),
    sa.Column('parent_node', sa.String(), nullable=True),
    sa.Column('mechanism_id', sa.String(), nullable=True),
    sa.Column('candidate_count', sa.Integer(), nullable=True),
    sa.Column('returned_count', sa.Integer(), nullable=True),
    sa.Column('cache_hit', sa.Integer(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_stage_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_stage_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_stage_cache_fingerprint'), ['fingerprint'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('email_alerts_enabled', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('knowledge_version', sa.String(), nullable=True),
    sa.Column('summary_short', sa.String(), nullable=True),
    sa.Column('summary_long', sa.Text(), nullable=True),
    sa.Column('is_unconfirmed', sa.Integer(), nullable=True),
    sa.Column('facts', sa.Text(), nullable=True),
    sa.Column('refinement_status', sa.String(), nullable=True),
    sa.Column('refinement_attempts', sa.Integer(), nullable=False),
    sa.Column('analysis_provider', sa.String(), nullable=True),
    sa.Column('analysis_quality', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'lang', name='uq_article_translation_lang')
    )
    op.create_table('company_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('alias_type', sa.String(), nullable=False),
    sa.Column('normalized', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized', 'company_id', name='uq_alias_normalized_company')
    )
    with op.batch_alter_table('company_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_aliases_normalized'), ['normalized'], unique=False)

    op.create_table('company_exposures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'dimension', name='uq_company_exposure_dimension')
    )
    with op.batch_alter_table('company_exposures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_exposures_company_id'), ['company_id'], unique=False)

    op.create_table('company_index_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('index_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'index_code', name='uq_company_index')
    )
    op.create_table('company_node_exposures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('node_key', sa.String(), nullable=False),
    sa.Column('exposure_exists', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('mechanism', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_alert_id', sa.Integer(), nullable=True),
    sa.Column('provenance_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'node_key', name='uq_company_node_exposure')
    )
    op.create_table('event_volatility_ranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('n_events', sa.Integer(), nullable=False),
    sa.Column('min_excess_move_pct', sa.Float(), nullable=False),
    sa.Column('median_excess_move_pct', sa.Float(), nullable=False),
    sa.Column('max_excess_move_pct', sa.Float(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level', 'company_id', 'sector', 'category', name='uq_event_vol_level_subject_category')
    )
    op.create_table('gemini_paid_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id')
    )
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_holdings_user_company')
    )
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('scrip_code', sa.String(), nullable=True),
    sa.Column('series', sa.String(), nullable=True),
    sa.Column('group_code', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_sme', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('face_value', sa.Float(), nullable=True),
    sa.Column('listed_on', sa.Date(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'exchange', name='uq_listing_company_exchange'),
    sa.UniqueConstraint('exchange', 'symbol', name='uq_listing_exchange_symbol')
    )
    op.create_table('supply_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('relation', sa.String(), nullable=False),
    sa.Column('counterparty_name', sa.String(), nullable=False),
    sa.Column('counterparty_company_id', sa.Integer(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('source_agency', sa.String(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['counterparty_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'relation', 'counterparty_name', name='uq_supply_link_company_relation_counterparty')
    )
    op.create_table('user_watchlist_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', name='uq_watchlist_category_user_category')
    )
    op.create_table('user_watchlist_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_watchlist_company_user_company')
    )
    op.create_table('alert_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('magnitude_low', sa.Float(), nullable=False),
    sa.Column('magnitude_high', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('key_points_json', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('time_horizon', sa.String(), nullable=False),
    sa.Column('basis', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('reasons_json', sa.Text(), nullable=True),
    sa.Column('evidence_refs_json', sa.Text(), nullable=True),
    sa.Column('risks_json', sa.Text(), nullable=True),
    sa.Column('assumptions_json', sa.Text(), nullable=True),
    sa.Column('unknowns_json', sa.Text(), nullable=True),
    sa.Column('alternative_hypothesis', sa.Text(), nullable=True),
    sa.Column('confidence_band', sa.String(), nullable=True),
    sa.Column('confidence_contributors_json', sa.Text(), nullable=True),
    sa.Column('confidence_penalties_json', sa.Text(), nullable=True),
    sa.Column('rulebook_ids_json', sa.Text(), nullable=True),
    sa.Column('price_at_analysis', sa.Float(), nullable=True),
    sa.Column('return_1m', sa.Float(), nullable=True),
    sa.Column('return_3m', sa.Float(), nullable=True),
    sa.Column('contradiction_note', sa.Text(), nullable=True),
    sa.Column('impact_level', sa.String(), nullable=False),
    sa.Column('parent_company_id', sa.Integer(), nullable=True),
    sa.Column('why', sa.Text(), nullable=True),
    sa.Column('causal_distance', sa.Integer(), nullable=True),
    sa.Column('impact_strength', sa.Float(), nullable=True),
    sa.Column('confidence_f', sa.Float(), nullable=True),
    sa.Column('materiality', sa.Float(), nullable=True),
    sa.Column('causal_parent_type', sa.String(), nullable=True),
    sa.Column('causal_parent_id', sa.String(), nullable=True),
    sa.Column('mechanism', sa.Text(), nullable=True),
    sa.Column('channels_json', sa.Text(), nullable=True),
    sa.Column('economic_effect', sa.String(), nullable=True),
    sa.Column('display_tier', sa.String(), nullable=True),
    sa.Column('gate_state', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['parent_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_ripple_layers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('tickers_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(), nullable=False),
    sa.Column('summary_short', sa.String(), nullable=True),
    sa.Column('summary_long', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id', 'lang', name='uq_alert_translation_lang')
    )
    op.create_table('cascade_gaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('impact_level', sa.String(), nullable=False),
    sa.Column('parent_ticker', sa.String(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_decision_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('final_state', sa.String(), nullable=False),
    sa.Column('display_tier', sa.String(), nullable=False),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('gates_passed_json', sa.Text(), nullable=True),
    sa.Column('evidence_class', sa.String(), nullable=True),
    sa.Column('materiality_grade', sa.String(), nullable=True),
    sa.Column('candidate_json', sa.Text(), nullable=True),
    sa.Column('analysis_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_decision_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_decision_records_alert_id'), ['alert_id'], unique=False)

    op.create_table('impact_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('from_company_id', sa.Integer(), nullable=True),
    sa.Column('from_node_kind', sa.String(), nullable=False),
    sa.Column('from_label', sa.String(), nullable=False),
    sa.Column('to_company_id', sa.Integer(), nullable=True),
    sa.Column('to_node_kind', sa.String(), nullable=False),
    sa.Column('to_label', sa.String(), nullable=False),
    sa.Column('relation', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parent_type', sa.String(), nullable=True),
    sa.Column('child_type', sa.String(), nullable=True),
    sa.Column('causal_distance', sa.Integer(), nullable=True),
    sa.Column('impact_strength', sa.Float(), nullable=True),
    sa.Column('confidence_f', sa.Float(), nullable=True),
    sa.Column('materiality', sa.Float(), nullable=True),
    sa.Column('time_horizon', sa.String(), nullable=True),
    sa.Column('economic_effect', sa.String(), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['from_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['to_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('raw_move_pct', sa.Float(), nullable=True),
    sa.Column('sector_move_pct', sa.Float(), nullable=True),
    sa.Column('benchmark_ticker', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('excess_move_pct', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('avg_volume_20d', sa.Float(), nullable=True),
    sa.Column('volume_multiple', sa.Float(), nullable=True),
    sa.Column('delivery_pct', sa.Float(), nullable=True),
    sa.Column('vol_normalized', sa.Float(), nullable=True),
    sa.Column('materiality', sa.Float(), nullable=True),
    sa.Column('avg_traded_value', sa.Float(), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('measurement_status', sa.String(), nullable=False),
    sa.Column('last_bar_date', sa.String(), nullable=True),
    sa.Column('bar_complete', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id', 'company_id', name='uq_market_move_alert_company')
    )
    op.create_table('timeline_effects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('horizon', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translation_failures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id', name='uq_translation_failure_alert')
    )
    op.create_table('alert_company_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_company_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('key_points_json', sa.Text(), nullable=False),
    sa.Column('why', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_company_id'], ['alert_companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_company_id', 'lang', name='uq_alert_company_translation_lang')
    )
    op.create_table('calibration_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_company_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('magnitude_actual', sa.Float(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('sampled_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_company_id'], ['alert_companies.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_company_id', 'horizon_days', name='uq_calibration_alert_company_horizon')
    )
    op.create_table('car_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_company_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('day0_excess_move_pct', sa.Float(), nullable=False),
    sa.Column('car_pct', sa.Float(), nullable=False),
    sa.Column('car_series_json', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_company_id'], ['alert_companies.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_company_id', name='uq_car_outcome_alert_company')
    )
    op.create_table('email_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alert_company_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alert_company_id'], ['alert_companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'alert_company_id', name='uq_notification_user_alert_company')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_notifications')
    op.drop_table('car_outcomes')
    op.drop_table('calibration_samples')
    op.drop_table('alert_company_translations')
    op.drop_table('translation_failures')
    op.drop_table('timeline_effects')
    op.drop_table('market_moves')
    op.drop_table('impact_edges')
    with op.batch_alter_table('company_decision_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_decision_records_alert_id'))

    op.drop_table('company_decision_records')
    op.drop_table('cascade_gaps')
    op.drop_table('alert_translations')
    op.drop_table('alert_ripple_layers')
    op.drop_table('alert_companies')
    op.drop_table('user_watchlist_companies')
    op.drop_table('user_watchlist_categories')
    op.drop_table('supply_links')
    op.drop_table('listings')
    op.drop_table('holdings')
    op.drop_table('gemini_paid_usage')
    op.drop_table('event_volatility_ranges')
    op.drop_table('company_node_exposures')
    op.drop_table('company_index_memberships')
    with op.batch_alter_table('company_exposures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_exposures_company_id'))

    op.drop_table('company_exposures')
    with op.batch_alter_table('company_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_aliases_normalized'))

    op.drop_table('company_aliases')
    op.drop_table('article_translations')
    op.drop_table('alerts')
    op.drop_table('users')
    with op.batch_alter_table('llm_stage_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_stage_cache_fingerprint'))

    op.drop_table('llm_stage_cache')
    op.drop_table('llm_call_usage')
    op.drop_table('ingestion_sources')
    op.drop_table('financial_snapshots')
    op.drop_table('companies')
    op.drop_table('category_translations')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index('ix_articles_url_hash')
        batch_op.drop_index('ix_articles_provider_article_id')

    op.drop_table('articles')
    op.drop_table('analysis_cache')
    # ### end Alembic commands ###
