"""evidence records

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-13 13:26:55.686800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #
    # Guarded (unlike 0001's unconditional creates): evidence_records is the
    # first BRAND NEW TABLE added since app.db.init_db()'s create_all()
    # started sharing schema ownership with Alembic (see app/db.py's
    # SCHEMA_MANAGED_BY comment). create_all() always builds every table
    # models.py currently declares -- including this one -- so a DB built
    # via the legacy init_db() bootstrap (tests/test_migrations.py::
    # test_upgrade_on_legacy_created_db simulates exactly this: create_all()
    # then `alembic stamp 0001`) already has this table before this
    # migration ever runs. _ADDED_COLUMNS solved the equivalent problem for
    # columns on EXISTING tables (ALTER TABLE ... ADD COLUMN, guarded by
    # _existing_columns); this is that same guard for a whole new table, and
    # the pattern any future migration that adds a table should follow.
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'evidence_records' not in inspector.get_table_names():
        op.create_table('evidence_records',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('event_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=True),
        sa.Column('mechanism_id', sa.String(), nullable=True),
        sa.Column('evidence_class', sa.String(), nullable=False),
        sa.Column('evidence_tier', sa.String(), nullable=False),
        sa.Column('source_type', sa.String(), nullable=False),
        sa.Column('source_name', sa.String(), nullable=False),
        sa.Column('source_url', sa.String(), nullable=True),
        sa.Column('source_date', sa.Date(), nullable=True),
        sa.Column('as_of_date', sa.Date(), nullable=True),
        sa.Column('quoted_text', sa.Text(), nullable=True),
        sa.Column('fact_text', sa.Text(), nullable=False),
        sa.Column('quality', sa.String(), nullable=True),
        sa.Column('reliability', sa.Float(), nullable=True),
        sa.Column('provenance_type', sa.String(), nullable=True),
        sa.Column('supports_claim', sa.Boolean(), nullable=False),
        sa.Column('supports_direction', sa.Boolean(), nullable=True),
        sa.Column('supports_materiality', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('review_after', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
        sa.ForeignKeyConstraint(['event_id'], ['alerts.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    existing_indexes = {ix['name'] for ix in inspector.get_indexes('evidence_records')} \
        if 'evidence_records' in inspector.get_table_names() else set()
    if 'ix_evidence_alert_company' not in existing_indexes:
        with op.batch_alter_table('evidence_records', schema=None) as batch_op:
            batch_op.create_index('ix_evidence_alert_company', ['event_id', 'company_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_records', schema=None) as batch_op:
        batch_op.drop_index('ix_evidence_alert_company')

    op.drop_table('evidence_records')
    # ### end Alembic commands ###
