from sqlalchemy.orm import Session

from app.models import Company

# Curated static list of ~500 real, well-known global large-cap companies, ~50
# per sector, spanning the SAME fixed SECTORS taxonomy used for Indian companies
# so sector-inference resolution works identically for both markets. Tickers are
# real NYSE/NASDAQ symbols (or ADRs) with NO .NS/.BO suffix -> infer_market ->
# "GLOBAL".
GLOBAL_COMPANIES: list[dict] = [
    # it
    {"ticker": "AAPL", "name": "Apple", "sector": "it"},
    {"ticker": "MSFT", "name": "Microsoft", "sector": "it"},
    {"ticker": "GOOGL", "name": "Alphabet", "sector": "it"},
    {"ticker": "NVDA", "name": "NVIDIA", "sector": "it"},
    {"ticker": "META", "name": "Meta Platforms", "sector": "it"},
    {"ticker": "ORCL", "name": "Oracle", "sector": "it"},
    {"ticker": "ADBE", "name": "Adobe", "sector": "it"},
    {"ticker": "CRM", "name": "Salesforce", "sector": "it"},
    {"ticker": "INTC", "name": "Intel", "sector": "it"},
    {"ticker": "AMD", "name": "Advanced Micro Devices", "sector": "it"},
    {"ticker": "IBM", "name": "IBM", "sector": "it"},
    {"ticker": "CSCO", "name": "Cisco Systems", "sector": "it"},
    {"ticker": "QCOM", "name": "Qualcomm", "sector": "it"},
    {"ticker": "TXN", "name": "Texas Instruments", "sector": "it"},
    {"ticker": "AVGO", "name": "Broadcom", "sector": "it"},
    {"ticker": "NOW", "name": "ServiceNow", "sector": "it"},
    {"ticker": "INTU", "name": "Intuit", "sector": "it"},
    {"ticker": "SAP", "name": "SAP SE", "sector": "it"},
    {"ticker": "SHOP", "name": "Shopify", "sector": "it"},
    {"ticker": "UBER", "name": "Uber Technologies", "sector": "it"},
    {"ticker": "ABNB", "name": "Airbnb", "sector": "it"},
    {"ticker": "SNOW", "name": "Snowflake", "sector": "it"},
    {"ticker": "PLTR", "name": "Palantir Technologies", "sector": "it"},
    {"ticker": "PANW", "name": "Palo Alto Networks", "sector": "it"},
    {"ticker": "CRWD", "name": "CrowdStrike", "sector": "it"},
    {"ticker": "ADSK", "name": "Autodesk", "sector": "it"},
    {"ticker": "WDAY", "name": "Workday", "sector": "it"},
    {"ticker": "TEAM", "name": "Atlassian", "sector": "it"},
    {"ticker": "NET", "name": "Cloudflare", "sector": "it"},
    {"ticker": "DDOG", "name": "Datadog", "sector": "it"},
    {"ticker": "ZS", "name": "Zscaler", "sector": "it"},
    {"ticker": "MU", "name": "Micron Technology", "sector": "it"},
    {"ticker": "HPQ", "name": "HP Inc.", "sector": "it"},
    {"ticker": "DELL", "name": "Dell Technologies", "sector": "it"},
    {"ticker": "ANET", "name": "Arista Networks", "sector": "it"},
    {"ticker": "FTNT", "name": "Fortinet", "sector": "it"},
    {"ticker": "SPLK", "name": "Splunk", "sector": "it"},
    {"ticker": "VMW", "name": "VMware", "sector": "it"},
    {"ticker": "EA", "name": "Electronic Arts", "sector": "it"},
    {"ticker": "ATVI", "name": "Activision Blizzard", "sector": "it"},
    {"ticker": "TTD", "name": "The Trade Desk", "sector": "it"},
    {"ticker": "TWLO", "name": "Twilio", "sector": "it"},
    {"ticker": "OKTA", "name": "Okta", "sector": "it"},
    {"ticker": "DOCU", "name": "DocuSign", "sector": "it"},
    {"ticker": "ZM", "name": "Zoom Video Communications", "sector": "it"},
    {"ticker": "PYPL", "name": "PayPal", "sector": "it"},
    {"ticker": "SQ", "name": "Block Inc.", "sector": "it"},
    {"ticker": "NFLX", "name": "Netflix", "sector": "it"},
    {"ticker": "SONY", "name": "Sony Group", "sector": "it"},
    {"ticker": "ADI", "name": "Analog Devices", "sector": "it"},

    # banking
    {"ticker": "JPM", "name": "JPMorgan Chase", "sector": "banking"},
    {"ticker": "BAC", "name": "Bank of America", "sector": "banking"},
    {"ticker": "WFC", "name": "Wells Fargo", "sector": "banking"},
    {"ticker": "C", "name": "Citigroup", "sector": "banking"},
    {"ticker": "GS", "name": "Goldman Sachs", "sector": "banking"},
    {"ticker": "MS", "name": "Morgan Stanley", "sector": "banking"},
    {"ticker": "HSBC", "name": "HSBC Holdings", "sector": "banking"},
    {"ticker": "BCS", "name": "Barclays", "sector": "banking"},
    {"ticker": "UBS", "name": "UBS Group", "sector": "banking"},
    {"ticker": "DB", "name": "Deutsche Bank", "sector": "banking"},
    {"ticker": "USB", "name": "U.S. Bancorp", "sector": "banking"},
    {"ticker": "PNC", "name": "PNC Financial Services", "sector": "banking"},
    {"ticker": "TFC", "name": "Truist Financial", "sector": "banking"},
    {"ticker": "COF", "name": "Capital One Financial", "sector": "banking"},
    {"ticker": "BK", "name": "Bank of New York Mellon", "sector": "banking"},
    {"ticker": "STT", "name": "State Street", "sector": "banking"},
    {"ticker": "SCHW", "name": "Charles Schwab", "sector": "banking"},
    {"ticker": "AXP", "name": "American Express", "sector": "banking"},
    {"ticker": "RY", "name": "Royal Bank of Canada", "sector": "banking"},
    {"ticker": "TD", "name": "Toronto-Dominion Bank", "sector": "banking"},
    {"ticker": "BMO", "name": "Bank of Montreal", "sector": "banking"},
    {"ticker": "BNS", "name": "Bank of Nova Scotia", "sector": "banking"},
    {"ticker": "ING", "name": "ING Groep", "sector": "banking"},
    {"ticker": "SAN", "name": "Banco Santander", "sector": "banking"},
    {"ticker": "BBVA", "name": "Banco Bilbao Vizcaya Argentaria", "sector": "banking"},
    {"ticker": "MUFG", "name": "Mitsubishi UFJ Financial Group", "sector": "banking"},
    {"ticker": "SMFG", "name": "Sumitomo Mitsui Financial Group", "sector": "banking"},
    {"ticker": "MFG", "name": "Mizuho Financial Group", "sector": "banking"},
    {"ticker": "NWG", "name": "NatWest Group", "sector": "banking"},
    {"ticker": "LYG", "name": "Lloyds Banking Group", "sector": "banking"},
    {"ticker": "ALLY", "name": "Ally Financial", "sector": "banking"},
    {"ticker": "FITB", "name": "Fifth Third Bancorp", "sector": "banking"},
    {"ticker": "KEY", "name": "KeyCorp", "sector": "banking"},
    {"ticker": "RF", "name": "Regions Financial", "sector": "banking"},
    {"ticker": "HBAN", "name": "Huntington Bancshares", "sector": "banking"},
    {"ticker": "CFG", "name": "Citizens Financial Group", "sector": "banking"},
    {"ticker": "ZION", "name": "Zions Bancorporation", "sector": "banking"},
    {"ticker": "CMA", "name": "Comerica", "sector": "banking"},
    {"ticker": "MTB", "name": "M&T Bank", "sector": "banking"},
    {"ticker": "NTRS", "name": "Northern Trust", "sector": "banking"},
    {"ticker": "DFS", "name": "Discover Financial Services", "sector": "banking"},
    {"ticker": "SYF", "name": "Synchrony Financial", "sector": "banking"},
    {"ticker": "AIG", "name": "American International Group", "sector": "banking"},
    {"ticker": "MET", "name": "MetLife", "sector": "banking"},
    {"ticker": "PRU", "name": "Prudential Financial", "sector": "banking"},
    {"ticker": "AFL", "name": "Aflac", "sector": "banking"},
    {"ticker": "TRV", "name": "Travelers Companies", "sector": "banking"},
    {"ticker": "ALL", "name": "Allstate", "sector": "banking"},
    {"ticker": "CB", "name": "Chubb Limited", "sector": "banking"},
    {"ticker": "PGR", "name": "Progressive Corporation", "sector": "banking"},

    # oil_gas
    {"ticker": "XOM", "name": "ExxonMobil", "sector": "oil_gas"},
    {"ticker": "CVX", "name": "Chevron", "sector": "oil_gas"},
    {"ticker": "SHEL", "name": "Shell", "sector": "oil_gas"},
    {"ticker": "BP", "name": "BP", "sector": "oil_gas"},
    {"ticker": "COP", "name": "ConocoPhillips", "sector": "oil_gas"},
    {"ticker": "TTE", "name": "TotalEnergies", "sector": "oil_gas"},
    {"ticker": "EQNR", "name": "Equinor", "sector": "oil_gas"},
    {"ticker": "ENB", "name": "Enbridge", "sector": "oil_gas"},
    {"ticker": "WMB", "name": "Williams Companies", "sector": "oil_gas"},
    {"ticker": "KMI", "name": "Kinder Morgan", "sector": "oil_gas"},
    {"ticker": "OXY", "name": "Occidental Petroleum", "sector": "oil_gas"},
    {"ticker": "EOG", "name": "EOG Resources", "sector": "oil_gas"},
    {"ticker": "SLB", "name": "Schlumberger", "sector": "oil_gas"},
    {"ticker": "HAL", "name": "Halliburton", "sector": "oil_gas"},
    {"ticker": "BKR", "name": "Baker Hughes", "sector": "oil_gas"},
    {"ticker": "PSX", "name": "Phillips 66", "sector": "oil_gas"},
    {"ticker": "MPC", "name": "Marathon Petroleum", "sector": "oil_gas"},
    {"ticker": "VLO", "name": "Valero Energy", "sector": "oil_gas"},
    {"ticker": "HES", "name": "Hess Corporation", "sector": "oil_gas"},
    {"ticker": "DVN", "name": "Devon Energy", "sector": "oil_gas"},
    {"ticker": "FANG", "name": "Diamondback Energy", "sector": "oil_gas"},
    {"ticker": "PXD", "name": "Pioneer Natural Resources", "sector": "oil_gas"},
    {"ticker": "APA", "name": "APA Corporation", "sector": "oil_gas"},
    {"ticker": "CTRA", "name": "Coterra Energy", "sector": "oil_gas"},
    {"ticker": "MRO", "name": "Marathon Oil", "sector": "oil_gas"},
    {"ticker": "OVV", "name": "Ovintiv", "sector": "oil_gas"},
    {"ticker": "TRGP", "name": "Targa Resources", "sector": "oil_gas"},
    {"ticker": "OKE", "name": "ONEOK", "sector": "oil_gas"},
    {"ticker": "LNG", "name": "Cheniere Energy", "sector": "oil_gas"},
    {"ticker": "ET", "name": "Energy Transfer", "sector": "oil_gas"},
    {"ticker": "EPD", "name": "Enterprise Products Partners", "sector": "oil_gas"},
    {"ticker": "MPLX", "name": "MPLX LP", "sector": "oil_gas"},
    {"ticker": "PAA", "name": "Plains All American Pipeline", "sector": "oil_gas"},
    {"ticker": "PBR", "name": "Petrobras", "sector": "oil_gas"},
    {"ticker": "E", "name": "Eni S.p.A.", "sector": "oil_gas"},
    {"ticker": "REPYY", "name": "Repsol", "sector": "oil_gas"},
    {"ticker": "GALP", "name": "Galp Energia", "sector": "oil_gas"},
    {"ticker": "WDS", "name": "Woodside Energy", "sector": "oil_gas"},
    {"ticker": "SU", "name": "Suncor Energy", "sector": "oil_gas"},
    {"ticker": "CNQ", "name": "Canadian Natural Resources", "sector": "oil_gas"},
    {"ticker": "IMO", "name": "Imperial Oil", "sector": "oil_gas"},
    {"ticker": "CVE", "name": "Cenovus Energy", "sector": "oil_gas"},
    {"ticker": "ARLP", "name": "Alliance Resource Partners", "sector": "oil_gas"},
    {"ticker": "RRC", "name": "Range Resources", "sector": "oil_gas"},
    {"ticker": "AR", "name": "Antero Resources", "sector": "oil_gas"},
    {"ticker": "SWN", "name": "Southwestern Energy", "sector": "oil_gas"},
    {"ticker": "CHK", "name": "Chesapeake Energy", "sector": "oil_gas"},
    {"ticker": "EQT", "name": "EQT Corporation", "sector": "oil_gas"},
    {"ticker": "NOV", "name": "NOV Inc.", "sector": "oil_gas"},
    {"ticker": "FTI", "name": "TechnipFMC", "sector": "oil_gas"},

    # auto
    {"ticker": "TSLA", "name": "Tesla", "sector": "auto"},
    {"ticker": "TM", "name": "Toyota Motor", "sector": "auto"},
    {"ticker": "VWAGY", "name": "Volkswagen", "sector": "auto"},
    {"ticker": "F", "name": "Ford Motor", "sector": "auto"},
    {"ticker": "GM", "name": "General Motors", "sector": "auto"},
    {"ticker": "STLA", "name": "Stellantis", "sector": "auto"},
    {"ticker": "HMC", "name": "Honda Motor", "sector": "auto"},
    {"ticker": "RACE", "name": "Ferrari", "sector": "auto"},
    {"ticker": "MBGYY", "name": "Mercedes-Benz Group", "sector": "auto"},
    {"ticker": "BMWYY", "name": "BMW", "sector": "auto"},
    {"ticker": "NSANY", "name": "Nissan Motor", "sector": "auto"},
    {"ticker": "HYMTF", "name": "Hyundai Motor", "sector": "auto"},
    {"ticker": "RIVN", "name": "Rivian Automotive", "sector": "auto"},
    {"ticker": "LCID", "name": "Lucid Group", "sector": "auto"},
    {"ticker": "NIO", "name": "NIO Inc.", "sector": "auto"},
    {"ticker": "LI", "name": "Li Auto", "sector": "auto"},
    {"ticker": "XPEV", "name": "XPeng", "sector": "auto"},
    {"ticker": "BYDDY", "name": "BYD Company", "sector": "auto"},
    {"ticker": "MGA", "name": "Magna International", "sector": "auto"},
    {"ticker": "APTV", "name": "Aptiv", "sector": "auto"},
    {"ticker": "BWA", "name": "BorgWarner", "sector": "auto"},
    {"ticker": "LEA", "name": "Lear Corporation", "sector": "auto"},
    {"ticker": "ALV", "name": "Autoliv", "sector": "auto"},
    {"ticker": "DAN", "name": "Dana Incorporated", "sector": "auto"},
    {"ticker": "GT", "name": "Goodyear Tire & Rubber", "sector": "auto"},
    {"ticker": "ADNT", "name": "Adient", "sector": "auto"},
    {"ticker": "HOG", "name": "Harley-Davidson", "sector": "auto"},
    {"ticker": "PII", "name": "Polaris Inc.", "sector": "auto"},
    {"ticker": "THO", "name": "Thor Industries", "sector": "auto"},
    {"ticker": "PATK", "name": "Patrick Industries", "sector": "auto"},
    {"ticker": "LKQ", "name": "LKQ Corporation", "sector": "auto"},
    {"ticker": "CPRT", "name": "Copart", "sector": "auto"},
    {"ticker": "KMX", "name": "CarMax", "sector": "auto"},
    {"ticker": "AN", "name": "AutoNation", "sector": "auto"},
    {"ticker": "PAG", "name": "Penske Automotive Group", "sector": "auto"},
    {"ticker": "GPI", "name": "Group 1 Automotive", "sector": "auto"},
    {"ticker": "ORLY", "name": "O'Reilly Automotive", "sector": "auto"},
    {"ticker": "AZO", "name": "AutoZone", "sector": "auto"},
    {"ticker": "AAP", "name": "Advance Auto Parts", "sector": "auto"},
    {"ticker": "DORM", "name": "Dorman Products", "sector": "auto"},
    {"ticker": "MNRO", "name": "Monro Inc.", "sector": "auto"},
    {"ticker": "SAH", "name": "Sonic Automotive", "sector": "auto"},
    {"ticker": "ABG", "name": "Asbury Automotive Group", "sector": "auto"},
    {"ticker": "CVCO", "name": "Cavco Industries", "sector": "auto"},
    {"ticker": "WGO", "name": "Winnebago Industries", "sector": "auto"},
    {"ticker": "FOXF", "name": "Fox Factory Holding", "sector": "auto"},
    {"ticker": "VC", "name": "Visteon Corporation", "sector": "auto"},
    {"ticker": "MOD", "name": "Modine Manufacturing", "sector": "auto"},
    {"ticker": "SMP", "name": "Standard Motor Products", "sector": "auto"},
    {"ticker": "GNTX", "name": "Gentex Corporation", "sector": "auto"},

    # pharma
    {"ticker": "PFE", "name": "Pfizer", "sector": "pharma"},
    {"ticker": "JNJ", "name": "Johnson & Johnson", "sector": "pharma"},
    {"ticker": "RHHBY", "name": "Roche Holding", "sector": "pharma"},
    {"ticker": "NVS", "name": "Novartis", "sector": "pharma"},
    {"ticker": "MRK", "name": "Merck & Co.", "sector": "pharma"},
    {"ticker": "ABBV", "name": "AbbVie", "sector": "pharma"},
    {"ticker": "LLY", "name": "Eli Lilly", "sector": "pharma"},
    {"ticker": "BMY", "name": "Bristol-Myers Squibb", "sector": "pharma"},
    {"ticker": "AZN", "name": "AstraZeneca", "sector": "pharma"},
    {"ticker": "SNY", "name": "Sanofi", "sector": "pharma"},
    {"ticker": "GSK", "name": "GSK plc", "sector": "pharma"},
    {"ticker": "TAK", "name": "Takeda Pharmaceutical", "sector": "pharma"},
    {"ticker": "NVO", "name": "Novo Nordisk", "sector": "pharma"},
    {"ticker": "AMGN", "name": "Amgen", "sector": "pharma"},
    {"ticker": "GILD", "name": "Gilead Sciences", "sector": "pharma"},
    {"ticker": "VRTX", "name": "Vertex Pharmaceuticals", "sector": "pharma"},
    {"ticker": "REGN", "name": "Regeneron Pharmaceuticals", "sector": "pharma"},
    {"ticker": "BIIB", "name": "Biogen", "sector": "pharma"},
    {"ticker": "ZTS", "name": "Zoetis", "sector": "pharma"},
    {"ticker": "MRNA", "name": "Moderna", "sector": "pharma"},
    {"ticker": "BNTX", "name": "BioNTech", "sector": "pharma"},
    {"ticker": "TEVA", "name": "Teva Pharmaceutical Industries", "sector": "pharma"},
    {"ticker": "VTRS", "name": "Viatris", "sector": "pharma"},
    {"ticker": "ALNY", "name": "Alnylam Pharmaceuticals", "sector": "pharma"},
    {"ticker": "BMRN", "name": "BioMarin Pharmaceutical", "sector": "pharma"},
    {"ticker": "INCY", "name": "Incyte Corporation", "sector": "pharma"},
    {"ticker": "JAZZ", "name": "Jazz Pharmaceuticals", "sector": "pharma"},
    {"ticker": "UTHR", "name": "United Therapeutics", "sector": "pharma"},
    {"ticker": "EXEL", "name": "Exelixis", "sector": "pharma"},
    {"ticker": "RPRX", "name": "Royalty Pharma", "sector": "pharma"},
    {"ticker": "ICLR", "name": "ICON plc", "sector": "pharma"},
    {"ticker": "IQV", "name": "IQVIA Holdings", "sector": "pharma"},
    {"ticker": "CRL", "name": "Charles River Laboratories", "sector": "pharma"},
    {"ticker": "CTLT", "name": "Catalent", "sector": "pharma"},
    {"ticker": "MTD", "name": "Mettler-Toledo", "sector": "pharma"},
    {"ticker": "A", "name": "Agilent Technologies", "sector": "pharma"},
    {"ticker": "WAT", "name": "Waters Corporation", "sector": "pharma"},
    {"ticker": "DGX", "name": "Quest Diagnostics", "sector": "pharma"},
    {"ticker": "LH", "name": "Labcorp Holdings", "sector": "pharma"},
    {"ticker": "HOLX", "name": "Hologic", "sector": "pharma"},
    {"ticker": "BAX", "name": "Baxter International", "sector": "pharma"},
    {"ticker": "BDX", "name": "Becton Dickinson", "sector": "pharma"},
    {"ticker": "SYK", "name": "Stryker Corporation", "sector": "pharma"},
    {"ticker": "MDT", "name": "Medtronic", "sector": "pharma"},
    {"ticker": "BSX", "name": "Boston Scientific", "sector": "pharma"},
    {"ticker": "EW", "name": "Edwards Lifesciences", "sector": "pharma"},
    {"ticker": "ISRG", "name": "Intuitive Surgical", "sector": "pharma"},
    {"ticker": "ALGN", "name": "Align Technology", "sector": "pharma"},
    {"ticker": "DXCM", "name": "DexCom", "sector": "pharma"},
    {"ticker": "PODD", "name": "Insulet Corporation", "sector": "pharma"},

    # fmcg
    {"ticker": "PG", "name": "Procter & Gamble", "sector": "fmcg"},
    {"ticker": "KO", "name": "Coca-Cola", "sector": "fmcg"},
    {"ticker": "PEP", "name": "PepsiCo", "sector": "fmcg"},
    {"ticker": "UL", "name": "Unilever", "sector": "fmcg"},
    {"ticker": "NSRGY", "name": "Nestle", "sector": "fmcg"},
    {"ticker": "CL", "name": "Colgate-Palmolive", "sector": "fmcg"},
    {"ticker": "KMB", "name": "Kimberly-Clark", "sector": "fmcg"},
    {"ticker": "MDLZ", "name": "Mondelez International", "sector": "fmcg"},
    {"ticker": "GIS", "name": "General Mills", "sector": "fmcg"},
    {"ticker": "K", "name": "Kellanova", "sector": "fmcg"},
    {"ticker": "HSY", "name": "Hershey Company", "sector": "fmcg"},
    {"ticker": "STZ", "name": "Constellation Brands", "sector": "fmcg"},
    {"ticker": "MO", "name": "Altria Group", "sector": "fmcg"},
    {"ticker": "PM", "name": "Philip Morris International", "sector": "fmcg"},
    {"ticker": "BTI", "name": "British American Tobacco", "sector": "fmcg"},
    {"ticker": "DEO", "name": "Diageo", "sector": "fmcg"},
    {"ticker": "BUD", "name": "Anheuser-Busch InBev", "sector": "fmcg"},
    {"ticker": "TAP", "name": "Molson Coors Beverage", "sector": "fmcg"},
    {"ticker": "KDP", "name": "Keurig Dr Pepper", "sector": "fmcg"},
    {"ticker": "MNST", "name": "Monster Beverage", "sector": "fmcg"},
    {"ticker": "CLX", "name": "Clorox", "sector": "fmcg"},
    {"ticker": "CHD", "name": "Church & Dwight", "sector": "fmcg"},
    {"ticker": "EL", "name": "Estee Lauder Companies", "sector": "fmcg"},
    {"ticker": "KVUE", "name": "Kenvue", "sector": "fmcg"},
    {"ticker": "HRL", "name": "Hormel Foods", "sector": "fmcg"},
    {"ticker": "CAG", "name": "Conagra Brands", "sector": "fmcg"},
    {"ticker": "SJM", "name": "J.M. Smucker Company", "sector": "fmcg"},
    {"ticker": "CPB", "name": "Campbell Soup Company", "sector": "fmcg"},
    {"ticker": "MKC", "name": "McCormick & Company", "sector": "fmcg"},
    {"ticker": "TSN", "name": "Tyson Foods", "sector": "fmcg"},
    {"ticker": "ADM", "name": "Archer-Daniels-Midland", "sector": "fmcg"},
    {"ticker": "BG", "name": "Bunge Global", "sector": "fmcg"},
    {"ticker": "INGR", "name": "Ingredion", "sector": "fmcg"},
    {"ticker": "LW", "name": "Lamb Weston Holdings", "sector": "fmcg"},
    {"ticker": "POST", "name": "Post Holdings", "sector": "fmcg"},
    {"ticker": "FLO", "name": "Flowers Foods", "sector": "fmcg"},
    {"ticker": "TWNK", "name": "Hostess Brands", "sector": "fmcg"},
    {"ticker": "USFD", "name": "US Foods Holding", "sector": "fmcg"},
    {"ticker": "SYY", "name": "Sysco Corporation", "sector": "fmcg"},
    {"ticker": "KHC", "name": "Kraft Heinz", "sector": "fmcg"},
    {"ticker": "WBA", "name": "Walgreens Boots Alliance", "sector": "fmcg"},
    {"ticker": "COTY", "name": "Coty Inc.", "sector": "fmcg"},
    {"ticker": "CCEP", "name": "Coca-Cola Europacific Partners", "sector": "fmcg"},
    {"ticker": "KOF", "name": "Coca-Cola FEMSA", "sector": "fmcg"},
    {"ticker": "FMX", "name": "Fomento Economico Mexicano", "sector": "fmcg"},
    {"ticker": "DANOY", "name": "Danone", "sector": "fmcg"},
    {"ticker": "RBGLY", "name": "Reckitt Benckiser Group", "sector": "fmcg"},
    {"ticker": "HENKY", "name": "Henkel AG", "sector": "fmcg"},
    {"ticker": "BF.B", "name": "Brown-Forman", "sector": "fmcg"},
    {"ticker": "COST", "name": "Costco Wholesale", "sector": "fmcg"},

    # metals
    {"ticker": "MT", "name": "ArcelorMittal", "sector": "metals"},
    {"ticker": "RIO", "name": "Rio Tinto", "sector": "metals"},
    {"ticker": "BHP", "name": "BHP Group", "sector": "metals"},
    {"ticker": "VALE", "name": "Vale", "sector": "metals"},
    {"ticker": "AA", "name": "Alcoa", "sector": "metals"},
    {"ticker": "NUE", "name": "Nucor Corporation", "sector": "metals"},
    {"ticker": "STLD", "name": "Steel Dynamics", "sector": "metals"},
    {"ticker": "X", "name": "United States Steel", "sector": "metals"},
    {"ticker": "CLF", "name": "Cleveland-Cliffs", "sector": "metals"},
    {"ticker": "FCX", "name": "Freeport-McMoRan", "sector": "metals"},
    {"ticker": "SCCO", "name": "Southern Copper Corporation", "sector": "metals"},
    {"ticker": "TECK", "name": "Teck Resources", "sector": "metals"},
    {"ticker": "GLNCY", "name": "Glencore", "sector": "metals"},
    {"ticker": "AU", "name": "AngloGold Ashanti", "sector": "metals"},
    {"ticker": "NEM", "name": "Newmont Corporation", "sector": "metals"},
    {"ticker": "GOLD", "name": "Barrick Gold", "sector": "metals"},
    {"ticker": "AEM", "name": "Agnico Eagle Mines", "sector": "metals"},
    {"ticker": "KGC", "name": "Kinross Gold", "sector": "metals"},
    {"ticker": "FNV", "name": "Franco-Nevada", "sector": "metals"},
    {"ticker": "WPM", "name": "Wheaton Precious Metals", "sector": "metals"},
    {"ticker": "PAAS", "name": "Pan American Silver", "sector": "metals"},
    {"ticker": "HL", "name": "Hecla Mining", "sector": "metals"},
    {"ticker": "CDE", "name": "Coeur Mining", "sector": "metals"},
    {"ticker": "MP", "name": "MP Materials", "sector": "metals"},
    {"ticker": "ALB", "name": "Albemarle Corporation", "sector": "metals"},
    {"ticker": "LTHM", "name": "Livent Corporation", "sector": "metals"},
    {"ticker": "SQM", "name": "Sociedad Quimica y Minera", "sector": "metals"},
    {"ticker": "LAC", "name": "Lithium Americas", "sector": "metals"},
    {"ticker": "PLL", "name": "Piedmont Lithium", "sector": "metals"},
    {"ticker": "CENX", "name": "Century Aluminum", "sector": "metals"},
    {"ticker": "KALU", "name": "Kaiser Aluminum", "sector": "metals"},
    {"ticker": "WOR", "name": "Worthington Industries", "sector": "metals"},
    {"ticker": "RS", "name": "Reliance Steel & Aluminum", "sector": "metals"},
    {"ticker": "CMC", "name": "Commercial Metals Company", "sector": "metals"},
    {"ticker": "SXC", "name": "SunCoke Energy", "sector": "metals"},
    {"ticker": "ATI", "name": "ATI Inc.", "sector": "metals"},
    {"ticker": "CRS", "name": "Carpenter Technology", "sector": "metals"},
    {"ticker": "HAYN", "name": "Haynes International", "sector": "metals"},
    {"ticker": "MTRN", "name": "Materion Corporation", "sector": "metals"},
    {"ticker": "OLN", "name": "Olin Corporation", "sector": "metals"},
    {"ticker": "LYB", "name": "LyondellBasell Industries", "sector": "metals"},
    {"ticker": "DOW", "name": "Dow Inc.", "sector": "metals"},
    {"ticker": "DD", "name": "DuPont de Nemours", "sector": "metals"},
    {"ticker": "CE", "name": "Celanese Corporation", "sector": "metals"},
    {"ticker": "EMN", "name": "Eastman Chemical Company", "sector": "metals"},
    {"ticker": "ASH", "name": "Ashland Inc.", "sector": "metals"},
    {"ticker": "FMC", "name": "FMC Corporation", "sector": "metals"},
    {"ticker": "IFF", "name": "International Flavors & Fragrances", "sector": "metals"},
    {"ticker": "LIN", "name": "Linde plc", "sector": "metals"},
    {"ticker": "PPG", "name": "PPG Industries", "sector": "metals"},

    # telecom
    {"ticker": "VZ", "name": "Verizon Communications", "sector": "telecom"},
    {"ticker": "T", "name": "AT&T", "sector": "telecom"},
    {"ticker": "VOD", "name": "Vodafone Group", "sector": "telecom"},
    {"ticker": "DTEGY", "name": "Deutsche Telekom", "sector": "telecom"},
    {"ticker": "TMUS", "name": "T-Mobile US", "sector": "telecom"},
    {"ticker": "TEF", "name": "Telefonica", "sector": "telecom"},
    {"ticker": "ORAN", "name": "Orange S.A.", "sector": "telecom"},
    {"ticker": "CHL", "name": "China Mobile", "sector": "telecom"},
    {"ticker": "NTT", "name": "Nippon Telegraph and Telephone", "sector": "telecom"},
    {"ticker": "KT", "name": "KT Corporation", "sector": "telecom"},
    {"ticker": "SKM", "name": "SK Telecom", "sector": "telecom"},
    {"ticker": "TU", "name": "TELUS Corporation", "sector": "telecom"},
    {"ticker": "BCE", "name": "BCE Inc.", "sector": "telecom"},
    {"ticker": "RCI", "name": "Rogers Communications", "sector": "telecom"},
    {"ticker": "AMX", "name": "America Movil", "sector": "telecom"},
    {"ticker": "TIMB", "name": "TIM S.A.", "sector": "telecom"},
    {"ticker": "VIV", "name": "Telefonica Brasil", "sector": "telecom"},
    {"ticker": "CHTR", "name": "Charter Communications", "sector": "telecom"},
    {"ticker": "CMCSA", "name": "Comcast Corporation", "sector": "telecom"},
    {"ticker": "LUMN", "name": "Lumen Technologies", "sector": "telecom"},
    {"ticker": "USM", "name": "United States Cellular", "sector": "telecom"},
    {"ticker": "TDS", "name": "Telephone and Data Systems", "sector": "telecom"},
    {"ticker": "ATUS", "name": "Altice USA", "sector": "telecom"},
    {"ticker": "LBRDK", "name": "Liberty Broadband", "sector": "telecom"},
    {"ticker": "LBTYA", "name": "Liberty Global", "sector": "telecom"},
    {"ticker": "SBAC", "name": "SBA Communications", "sector": "telecom"},
    {"ticker": "AMT", "name": "American Tower", "sector": "telecom"},
    {"ticker": "CCI", "name": "Crown Castle", "sector": "telecom"},
    {"ticker": "EQIX", "name": "Equinix", "sector": "telecom"},
    {"ticker": "DLR", "name": "Digital Realty Trust", "sector": "telecom"},
    {"ticker": "IRDM", "name": "Iridium Communications", "sector": "telecom"},
    {"ticker": "GSAT", "name": "Globalstar", "sector": "telecom"},
    {"ticker": "VSAT", "name": "Viasat", "sector": "telecom"},
    {"ticker": "HPE", "name": "Hewlett Packard Enterprise", "sector": "telecom"},
    {"ticker": "JNPR", "name": "Juniper Networks", "sector": "telecom"},
    {"ticker": "CIEN", "name": "Ciena Corporation", "sector": "telecom"},
    {"ticker": "NOK", "name": "Nokia Corporation", "sector": "telecom"},
    {"ticker": "MSI", "name": "Motorola Solutions", "sector": "telecom"},
    {"ticker": "UI", "name": "Ubiquiti Inc.", "sector": "telecom"},
    {"ticker": "CALX", "name": "Calix Inc.", "sector": "telecom"},
    {"ticker": "INFN", "name": "Infinera Corporation", "sector": "telecom"},
    {"ticker": "GOGO", "name": "Gogo Inc.", "sector": "telecom"},
    {"ticker": "SATS", "name": "EchoStar Corporation", "sector": "telecom"},
    {"ticker": "ORBC", "name": "ORBCOMM", "sector": "telecom"},
    {"ticker": "ATEX", "name": "Anterix", "sector": "telecom"},
    {"ticker": "SHEN", "name": "Shenandoah Telecommunications", "sector": "telecom"},
    {"ticker": "CCOI", "name": "Cogent Communications", "sector": "telecom"},
    {"ticker": "IDT", "name": "IDT Corporation", "sector": "telecom"},
    {"ticker": "FYBR", "name": "Frontier Communications", "sector": "telecom"},
    {"ticker": "WOW", "name": "WideOpenWest", "sector": "telecom"},

    # infra
    {"ticker": "CAT", "name": "Caterpillar", "sector": "infra"},
    {"ticker": "DE", "name": "Deere & Company", "sector": "infra"},
    {"ticker": "HON", "name": "Honeywell International", "sector": "infra"},
    {"ticker": "MMM", "name": "3M", "sector": "infra"},
    {"ticker": "GE", "name": "General Electric", "sector": "infra"},
    {"ticker": "ETN", "name": "Eaton Corporation", "sector": "infra"},
    {"ticker": "EMR", "name": "Emerson Electric", "sector": "infra"},
    {"ticker": "ITW", "name": "Illinois Tool Works", "sector": "infra"},
    {"ticker": "PH", "name": "Parker Hannifin", "sector": "infra"},
    {"ticker": "ROK", "name": "Rockwell Automation", "sector": "infra"},
    {"ticker": "DOV", "name": "Dover Corporation", "sector": "infra"},
    {"ticker": "XYL", "name": "Xylem Inc.", "sector": "infra"},
    {"ticker": "AME", "name": "AMETEK", "sector": "infra"},
    {"ticker": "IEX", "name": "IDEX Corporation", "sector": "infra"},
    {"ticker": "FTV", "name": "Fortive Corporation", "sector": "infra"},
    {"ticker": "SWK", "name": "Stanley Black & Decker", "sector": "infra"},
    {"ticker": "CMI", "name": "Cummins Inc.", "sector": "infra"},
    {"ticker": "PCAR", "name": "PACCAR Inc.", "sector": "infra"},
    {"ticker": "WAB", "name": "Wabtec Corporation", "sector": "infra"},
    {"ticker": "URI", "name": "United Rentals", "sector": "infra"},
    {"ticker": "HEI", "name": "HEICO Corporation", "sector": "infra"},
    {"ticker": "TT", "name": "Trane Technologies", "sector": "infra"},
    {"ticker": "JCI", "name": "Johnson Controls International", "sector": "infra"},
    {"ticker": "CARR", "name": "Carrier Global", "sector": "infra"},
    {"ticker": "LII", "name": "Lennox International", "sector": "infra"},
    {"ticker": "AOS", "name": "A. O. Smith Corporation", "sector": "infra"},
    {"ticker": "MAS", "name": "Masco Corporation", "sector": "infra"},
    {"ticker": "VMC", "name": "Vulcan Materials Company", "sector": "infra"},
    {"ticker": "MLM", "name": "Martin Marietta Materials", "sector": "infra"},
    {"ticker": "EXP", "name": "Eagle Materials", "sector": "infra"},
    {"ticker": "USCR", "name": "U.S. Concrete", "sector": "infra"},
    {"ticker": "SUM", "name": "Summit Materials", "sector": "infra"},
    {"ticker": "CX", "name": "Cemex", "sector": "infra"},
    {"ticker": "JHX", "name": "James Hardie Industries", "sector": "infra"},
    {"ticker": "BLDR", "name": "Builders FirstSource", "sector": "infra"},
    {"ticker": "POOL", "name": "Pool Corporation", "sector": "infra"},
    {"ticker": "FAST", "name": "Fastenal Company", "sector": "infra"},
    {"ticker": "GWW", "name": "W.W. Grainger", "sector": "infra"},
    {"ticker": "WSO", "name": "Watsco Inc.", "sector": "infra"},
    {"ticker": "SITE", "name": "SiteOne Landscape Supply", "sector": "infra"},
    {"ticker": "WCC", "name": "WESCO International", "sector": "infra"},
    {"ticker": "AXTA", "name": "Axalta Coating Systems", "sector": "infra"},
    {"ticker": "RPM", "name": "RPM International", "sector": "infra"},
    {"ticker": "PKG", "name": "Packaging Corporation of America", "sector": "infra"},
    {"ticker": "IP", "name": "International Paper", "sector": "infra"},
    {"ticker": "WY", "name": "Weyerhaeuser Company", "sector": "infra"},
    {"ticker": "AVY", "name": "Avery Dennison Corporation", "sector": "infra"},
    {"ticker": "SEE", "name": "Sealed Air Corporation", "sector": "infra"},
    {"ticker": "ALLE", "name": "Allegion", "sector": "infra"},
    {"ticker": "DOOR", "name": "Masonite International", "sector": "infra"},

    # other
    {"ticker": "BRK.B", "name": "Berkshire Hathaway", "sector": "other"},
    {"ticker": "DIS", "name": "Walt Disney", "sector": "other"},
    {"ticker": "AMZN", "name": "Amazon.com", "sector": "other"},
    {"ticker": "V", "name": "Visa", "sector": "other"},
    {"ticker": "MA", "name": "Mastercard", "sector": "other"},
    {"ticker": "WMT", "name": "Walmart", "sector": "other"},
    {"ticker": "HD", "name": "Home Depot", "sector": "other"},
    {"ticker": "LOW", "name": "Lowe's Companies", "sector": "other"},
    {"ticker": "TGT", "name": "Target Corporation", "sector": "other"},
    {"ticker": "MCD", "name": "McDonald's", "sector": "other"},
    {"ticker": "SBUX", "name": "Starbucks", "sector": "other"},
    {"ticker": "NKE", "name": "Nike", "sector": "other"},
    {"ticker": "LULU", "name": "Lululemon Athletica", "sector": "other"},
    {"ticker": "YUM", "name": "Yum! Brands", "sector": "other"},
    {"ticker": "CMG", "name": "Chipotle Mexican Grill", "sector": "other"},
    {"ticker": "BKNG", "name": "Booking Holdings", "sector": "other"},
    {"ticker": "MAR", "name": "Marriott International", "sector": "other"},
    {"ticker": "HLT", "name": "Hilton Worldwide Holdings", "sector": "other"},
    {"ticker": "RCL", "name": "Royal Caribbean Group", "sector": "other"},
    {"ticker": "CCL", "name": "Carnival Corporation", "sector": "other"},
    {"ticker": "NCLH", "name": "Norwegian Cruise Line Holdings", "sector": "other"},
    {"ticker": "DAL", "name": "Delta Air Lines", "sector": "other"},
    {"ticker": "UAL", "name": "United Airlines Holdings", "sector": "other"},
    {"ticker": "AAL", "name": "American Airlines Group", "sector": "other"},
    {"ticker": "LUV", "name": "Southwest Airlines", "sector": "other"},
    {"ticker": "UPS", "name": "United Parcel Service", "sector": "other"},
    {"ticker": "FDX", "name": "FedEx Corporation", "sector": "other"},
    {"ticker": "UNP", "name": "Union Pacific Corporation", "sector": "other"},
    {"ticker": "CSX", "name": "CSX Corporation", "sector": "other"},
    {"ticker": "NSC", "name": "Norfolk Southern Corporation", "sector": "other"},
    {"ticker": "ODFL", "name": "Old Dominion Freight Line", "sector": "other"},
    {"ticker": "JBHT", "name": "J.B. Hunt Transport Services", "sector": "other"},
    {"ticker": "CHRW", "name": "C.H. Robinson Worldwide", "sector": "other"},
    {"ticker": "EXPD", "name": "Expeditor International", "sector": "other"},
    {"ticker": "XPO", "name": "XPO Inc.", "sector": "other"},
    {"ticker": "RTX", "name": "RTX Corporation", "sector": "other"},
    {"ticker": "LMT", "name": "Lockheed Martin", "sector": "other"},
    {"ticker": "NOC", "name": "Northrop Grumman", "sector": "other"},
    {"ticker": "GD", "name": "General Dynamics", "sector": "other"},
    {"ticker": "BA", "name": "Boeing Company", "sector": "other"},
    {"ticker": "LHX", "name": "L3Harris Technologies", "sector": "other"},
    {"ticker": "TXT", "name": "Textron", "sector": "other"},
    {"ticker": "HII", "name": "Huntington Ingalls Industries", "sector": "other"},
    {"ticker": "ECL", "name": "Ecolab", "sector": "other"},
    {"ticker": "WM", "name": "Waste Management", "sector": "other"},
    {"ticker": "RSG", "name": "Republic Services", "sector": "other"},
    {"ticker": "VRSK", "name": "Verisk Analytics", "sector": "other"},
    {"ticker": "CTAS", "name": "Cintas Corporation", "sector": "other"},
    {"ticker": "PAYX", "name": "Paychex", "sector": "other"},
    {"ticker": "ADP", "name": "Automatic Data Processing", "sector": "other"},
]


def load_global_companies(session: Session) -> int:
    """Upsert every GLOBAL_COMPANIES entry as a Company row.

    Mirrors load_companies_from_csv's query-before-insert upsert pattern
    (no reliance on catching a unique-constraint error). All rows get
    index_tier="GLOBAL_LARGE_CAP" and market_cap=None.
    """
    count = 0
    for entry in GLOBAL_COMPANIES:
        existing = session.query(Company).filter_by(ticker=entry["ticker"]).one_or_none()
        if existing:
            existing.name = entry["name"]
            existing.sector = entry["sector"]
            existing.index_tier = "GLOBAL_LARGE_CAP"
        else:
            session.add(Company(
                ticker=entry["ticker"], name=entry["name"], sector=entry["sector"],
                index_tier="GLOBAL_LARGE_CAP", market_cap=None,
            ))
        count += 1
    session.commit()
    return count
