# Static, curated data compiled from official NSE index-constituent CSVs
# (archives.nseindia.com / niftyindices.com), fetched 2026-07-10. Mirrors
# global_seed.py's pattern: baked-in static data rather than a live runtime
# fetch, because NSE's archive endpoints are bot-protected in a way that
# isn't reliably reachable from a plain server-side HTTP client.
#
# CAP_TIER_COMPANIES: the four cap-based tiers that partition the Nifty 500
# universe (50 + 50 + 150 + 250 = 500), each company tagged with its
# canonical NSE industry string (fed through loader._normalize_sector).
#
# EXTRA_COMPANIES: companies that show up in a sectoral/thematic index but
# fall outside the Nifty 500 cap-tier universe (smaller-cap sectoral
# constituents, e.g. Nifty PSU Bank's Punjab & Sind Bank, Nifty Media's
# regional/niche names). These get index_tier="OTHER".
#
# INDEX_MEMBERSHIPS: index_code -> list of bare NSE symbols (no ".NS"
# suffix) belonging to that index, one entry per official CSV. Includes the
# four cap-tier codes too (a company is a NIFTY50 member AND gets a
# CompanyIndexMembership row for it) plus NIFTY100/NIFTY500 (fetched
# directly from NSE as a cross-check against the union of the four tiers).

CAP_TIER_COMPANIES = {
    "NIFTY50": [
        {"ticker": "ADANIENT.NS", "name": "Adani Enterprises Ltd.", "industry": "Metals & Mining", "isin": "INE423A01024"},
        {"ticker": "ADANIPORTS.NS", "name": "Adani Ports and Special Economic Zone Ltd.", "industry": "Services", "isin": "INE742F01042"},
        {"ticker": "APOLLOHOSP.NS", "name": "Apollo Hospitals Enterprise Ltd.", "industry": "Healthcare", "isin": "INE437A01024"},
        {"ticker": "ASIANPAINT.NS", "name": "Asian Paints Ltd.", "industry": "Consumer Durables", "isin": "INE021A01026"},
        {"ticker": "AXISBANK.NS", "name": "Axis Bank Ltd.", "industry": "Financial Services", "isin": "INE238A01034"},
        {"ticker": "BAJAJ-AUTO.NS", "name": "Bajaj Auto Ltd.", "industry": "Automobile and Auto Components", "isin": "INE917I01010"},
        {"ticker": "BAJFINANCE.NS", "name": "Bajaj Finance Ltd.", "industry": "Financial Services", "isin": "INE296A01032"},
        {"ticker": "BAJAJFINSV.NS", "name": "Bajaj Finserv Ltd.", "industry": "Financial Services", "isin": "INE918I01026"},
        {"ticker": "BEL.NS", "name": "Bharat Electronics Ltd.", "industry": "Capital Goods", "isin": "INE263A01024"},
        {"ticker": "BHARTIARTL.NS", "name": "Bharti Airtel Ltd.", "industry": "Telecommunication", "isin": "INE397D01024"},
        {"ticker": "CIPLA.NS", "name": "Cipla Ltd.", "industry": "Healthcare", "isin": "INE059A01026"},
        {"ticker": "COALINDIA.NS", "name": "Coal India Ltd.", "industry": "Oil Gas & Consumable Fuels", "isin": "INE522F01014"},
        {"ticker": "DRREDDY.NS", "name": "Dr. Reddy's Laboratories Ltd.", "industry": "Healthcare", "isin": "INE089A01031"},
        {"ticker": "EICHERMOT.NS", "name": "Eicher Motors Ltd.", "industry": "Automobile and Auto Components", "isin": "INE066A01021"},
        {"ticker": "ETERNAL.NS", "name": "Eternal Ltd.", "industry": "Consumer Services", "isin": "INE758T01015"},
        {"ticker": "GRASIM.NS", "name": "Grasim Industries Ltd.", "industry": "Construction Materials", "isin": "INE047A01021"},
        {"ticker": "HCLTECH.NS", "name": "HCL Technologies Ltd.", "industry": "Information Technology", "isin": "INE860A01027"},
        {"ticker": "HDFCBANK.NS", "name": "HDFC Bank Ltd.", "industry": "Financial Services", "isin": "INE040A01034"},
        {"ticker": "HDFCLIFE.NS", "name": "HDFC Life Insurance Company Ltd.", "industry": "Financial Services", "isin": "INE795G01014"},
        {"ticker": "HINDALCO.NS", "name": "Hindalco Industries Ltd.", "industry": "Metals & Mining", "isin": "INE038A01020"},
        {"ticker": "HINDUNILVR.NS", "name": "Hindustan Unilever Ltd.", "industry": "Fast Moving Consumer Goods", "isin": "INE030A01027"},
        {"ticker": "ICICIBANK.NS", "name": "ICICI Bank Ltd.", "industry": "Financial Services", "isin": "INE090A01021"},
        {"ticker": "INDIGO.NS", "name": "InterGlobe Aviation Ltd.", "industry": "Services", "isin": "INE646L01027"},
        {"ticker": "INFY.NS", "name": "Infosys Ltd.", "industry": "Information Technology", "isin": "INE009A01021"},
        {"ticker": "ITC.NS", "name": "ITC Ltd.", "industry": "Fast Moving Consumer Goods", "isin": "INE154A01025"},
        {"ticker": "JIOFIN.NS", "name": "Jio Financial Services Ltd.", "industry": "Financial Services", "isin": "INE758E01017"},
        {"ticker": "JSWSTEEL.NS", "name": "JSW Steel Ltd.", "industry": "Metals & Mining", "isin": "INE019A01038"},
        {"ticker": "KOTAKBANK.NS", "name": "Kotak Mahindra Bank Ltd.", "industry": "Financial Services", "isin": "INE237A01036"},
        {"ticker": "LT.NS", "name": "Larsen & Toubro Ltd.", "industry": "Construction", "isin": "INE018A01030"},
        {"ticker": "M&M.NS", "name": "Mahindra & Mahindra Ltd.", "industry": "Automobile and Auto Components", "isin": "INE101A01026"},
        {"ticker": "MARUTI.NS", "name": "Maruti Suzuki India Ltd.", "industry": "Automobile and Auto Components", "isin": "INE585B01010"},
        {"ticker": "MAXHEALTH.NS", "name": "Max Healthcare Institute Ltd.", "industry": "Healthcare", "isin": "INE027H01010"},
        {"ticker": "NESTLEIND.NS", "name": "Nestle India Ltd.", "industry": "Fast Moving Consumer Goods", "isin": "INE239A01024"},
        {"ticker": "NTPC.NS", "name": "NTPC Ltd.", "industry": "Power", "isin": "INE733E01010"},
        {"ticker": "ONGC.NS", "name": "Oil & Natural Gas Corporation Ltd.", "industry": "Oil Gas & Consumable Fuels", "isin": "INE213A01029"},
        {"ticker": "POWERGRID.NS", "name": "Power Grid Corporation of India Ltd.", "industry": "Power", "isin": "INE752E01010"},
        {"ticker": "RELIANCE.NS", "name": "Reliance Industries Ltd.", "industry": "Oil Gas & Consumable Fuels", "isin": "INE002A01018"},
        {"ticker": "SBILIFE.NS", "name": "SBI Life Insurance Company Ltd.", "industry": "Financial Services", "isin": "INE123W01016"},
        {"ticker": "SHRIRAMFIN.NS", "name": "Shriram Finance Ltd.", "industry": "Financial Services", "isin": "INE721A01047"},
        {"ticker": "SBIN.NS", "name": "State Bank of India", "industry": "Financial Services", "isin": "INE062A01020"},
        {"ticker": "SUNPHARMA.NS", "name": "Sun Pharmaceutical Industries Ltd.", "industry": "Healthcare", "isin": "INE044A01036"},
        {"ticker": "TCS.NS", "name": "Tata Consultancy Services Ltd.", "industry": "Information Technology", "isin": "INE467B01029"},
        {"ticker": "TATACONSUM.NS", "name": "Tata Consumer Products Ltd.", "industry": "Fast Moving Consumer Goods", "isin": "INE192A01025"},
        {"ticker": "TMPV.NS", "name": "Tata Motors Passenger Vehicles Ltd.", "industry": "Automobile and Auto Components", "isin": "INE155A01022"},
        {"ticker": "TATASTEEL.NS", "name": "Tata Steel Ltd.", "industry": "Metals & Mining", "isin": "INE081A01020"},
        {"ticker": "TECHM.NS", "name": "Tech Mahindra Ltd.", "industry": "Information Technology", "isin": "INE669C01036"},
        {"ticker": "TITAN.NS", "name": "Titan Company Ltd.", "industry": "Consumer Durables", "isin": "INE280A01028"},
        {"ticker": "TRENT.NS", "name": "Trent Ltd.", "industry": "Consumer Services", "isin": "INE849A01020"},
        {"ticker": "ULTRACEMCO.NS", "name": "UltraTech Cement Ltd.", "industry": "Construction Materials", "isin": "INE481G01011"},
        {"ticker": "WIPRO.NS", "name": "Wipro Ltd.", "industry": "Information Technology", "isin": "INE075A01022"},
    ],
    "NIFTYNEXT50": [
        {"ticker": "ABB.NS", "name": "ABB India Ltd.", "industry": "Capital Goods", "isin": "INE117A01022"},
        {"ticker": "ADANIENSOL.NS", "name": "Adani Energy Solutions Ltd.", "industry": "Power", "isin": "INE931S01010"},
        {"ticker": "ADANIGREEN.NS", "name": "Adani Green Energy Ltd.", "industry": "Power", "isin": "INE364U01010"},
        {"ticker": "ADANIPOWER.NS", "name": "Adani Power Ltd.", "industry": "Power", "isin": "INE814H01029"},
        {"ticker": "AMBUJACEM.NS", "name": "Ambuja Cements Ltd.", "industry": "Construction Materials", "isin": "INE079A01024"},
        {"ticker": "DMART.NS", "name": "Avenue Supermarts Ltd.", "industry": "Consumer Services", "isin": "INE192R01011"},
        {"ticker": "BAJAJHLDNG.NS", "name": "Bajaj Holdings & Investment Ltd.", "industry": "Financial Services", "isin": "INE118A01012"},
        {"ticker": "BANKBARODA.NS", "name": "Bank of Baroda", "industry": "Financial Services", "isin": "INE028A01039"},
        {"ticker": "BPCL.NS", "name": "Bharat Petroleum Corporation Ltd.", "industry": "Oil Gas & Consumable Fuels", "isin": "INE029A01011"},
        {"ticker": "BOSCHLTD.NS", "name": "Bosch Ltd.", "industry": "Automobile and Auto Components", "isin": "INE323A01026"},
        {"ticker": "BRITANNIA.NS", "name": "Britannia Industries Ltd.", "industry": "Fast Moving Consumer Goods", "isin": "INE216A01030"},
        {"ticker": "CGPOWER.NS", "name": "CG Power and Industrial Solutions Ltd.", "industry": "Capital Goods", "isin": "INE067A01029"},
        {"ticker": "CANBK.NS", "name": "Canara Bank", "industry": "Financial Services", "isin": "INE476A01022"},
        {"ticker": "CHOLAFIN.NS", "name": "Cholamandalam Investment and Finance Company Ltd.", "industry": "Financial Services", "isin": "INE121A01024"},
        {"ticker": "CUMMINSIND.NS", "name": "Cummins India Ltd.", "industry": "Capital Goods", "isin": "INE298A01020"},
        {"ticker": "DLF.NS", "name": "DLF Ltd.", "industry": "Realty", "isin": "INE271C01023"},
        {"ticker": "DIVISLAB.NS", "name": "Divi's Laboratories Ltd.", "industry": "Healthcare", "isin": "INE361B01024"},
        {"ticker": "GAIL.NS", "name": "GAIL (India) Ltd.", "industry": "Oil Gas & Consumable Fuels", "isin": "INE129A01019"},
        {"ticker": "GODREJCP.NS", "name": "Godrej Consumer Products Ltd.", "industry": "Fast Moving Consumer Goods", "isin": "INE102D01028"},
        {"ticker": "HDFCAMC.NS", "name": "HDFC Asset Management Company Ltd.", "industry": "Financial Services", "isin": "INE127D01025"},
        {"ticker": "HAL.NS", "name": "Hindustan Aeronautics Ltd.", "industry": "Capital Goods", "isin": "INE066F01020"},
        {"ticker": "HINDZINC.NS", "name": "Hindustan Zinc Ltd.", "industry": "Metals & Mining", "isin": "INE267A01025"},
        {"ticker": "HYUNDAI.NS", "name": "Hyundai Motor India Ltd.", "industry": "Automobile and Auto Components", "isin": "INE0V6F01027"},
        {"ticker": "INDHOTEL.NS", "name": "Indian Hotels Co. Ltd.", "industry": "Consumer Services", "isin": "INE053A01029"},
        {"ticker": "IOC.NS", "name": "Indian Oil Corporation Ltd.", "industry": "Oil Gas & Consumable Fuels", "isin": "INE242A01010"},
        {"ticker": "IRFC.NS", "name": "Indian Railway Finance Corporation Ltd.", "industry": "Financial Services", "isin": "INE053F01010"},
        {"ticker": "JINDALSTEL.NS", "name": "Jindal Steel Ltd.", "industry": "Metals & Mining", "isin": "INE749A01030"},
        {"ticker": "LTM.NS", "name": "LTM Ltd.", "industry": "Information Technology", "isin": "INE214T01019"},
        {"ticker": "LODHA.NS", "name": "Lodha Developers Ltd.", "industry": "Realty", "isin": "INE670K01029"},
        {"ticker": "MAZDOCK.NS", "name": "Mazagoan Dock Shipbuilders Ltd.", "industry": "Capital Goods", "isin": "INE249Z01020"},
        {"ticker": "MUTHOOTFIN.NS", "name": "Muthoot Finance Ltd.", "industry": "Financial Services", "isin": "INE414G01012"},
        {"ticker": "PIDILITIND.NS", "name": "Pidilite Industries Ltd.", "industry": "Chemicals", "isin": "INE318A01026"},
        {"ticker": "PFC.NS", "name": "Power Finance Corporation Ltd.", "industry": "Financial Services", "isin": "INE134E01011"},
        {"ticker": "PNB.NS", "name": "Punjab National Bank", "industry": "Financial Services", "isin": "INE160A01022"},
        {"ticker": "RECLTD.NS", "name": "REC Ltd.", "industry": "Financial Services", "isin": "INE020B01018"},
        {"ticker": "MOTHERSON.NS", "name": "Samvardhana Motherson International Ltd.", "industry": "Automobile and Auto Components", "isin": "INE775A01035"},
        {"ticker": "SHREECEM.NS", "name": "Shree Cement Ltd.", "industry": "Construction Materials", "isin": "INE070A01015"},
        {"ticker": "ENRIN.NS", "name": "Siemens Energy India Ltd.", "industry": "Capital Goods", "isin": "INE1NPP01017"},
        {"ticker": "SIEMENS.NS", "name": "Siemens Ltd.", "industry": "Capital Goods", "isin": "INE003A01024"},
        {"ticker": "SOLARINDS.NS", "name": "Solar Industries India Ltd.", "industry": "Chemicals", "isin": "INE343H01029"},
        {"ticker": "TVSMOTOR.NS", "name": "TVS Motor Company Ltd.", "industry": "Automobile and Auto Components", "isin": "INE494B01023"},
        {"ticker": "TATACAP.NS", "name": "Tata Capital Ltd.", "industry": "Financial Services", "isin": "INE976I01016"},
        {"ticker": "TMCV.NS", "name": "Tata Motors Ltd.", "industry": "Capital Goods", "isin": "INE1TAE01010"},
        {"ticker": "TATAPOWER.NS", "name": "Tata Power Co. Ltd.", "industry": "Power", "isin": "INE245A01021"},
        {"ticker": "TORNTPHARM.NS", "name": "Torrent Pharmaceuticals Ltd.", "industry": "Healthcare", "isin": "INE685A01028"},
        {"ticker": "UNIONBANK.NS", "name": "Union Bank of India", "industry": "Financial Services", "isin": "INE692A01016"},
        {"ticker": "UNITDSPR.NS", "name": "United Spirits Ltd.", "industry": "Fast Moving Consumer Goods", "isin": "INE854D01024"},
        {"ticker": "VBL.NS", "name": "Varun Beverages Ltd.", "industry": "Fast Moving Consumer Goods", "isin": "INE200M01039"},
        {"ticker": "VEDL.NS", "name": "Vedanta Ltd.", "industry": "Metals & Mining", "isin": "INE205A01025"},
        {"ticker": "ZYDUSLIFE.NS", "name": "Zydus Lifesciences Ltd.", "industry": "Healthcare", "isin": "INE010B01027"},
    ],
    "NIFTYMIDCAP150": [
        {"ticker": "360ONE.NS", "name": "360 ONE WAM Ltd.", "industry": "Financial Services", "isin": "INE466L01038"},
        {"ticker": "3MINDIA.NS", "name": "3M India Ltd.", "industry": "Diversified", "isin": "INE470A01017"},
        {"ticker": "ACC.NS", "name": "ACC Ltd.", "industry": "Construction Materials", "isin": "INE012A01025"},
        {"ticker": "AIAENG.NS", "name": "AIA Engineering Ltd.", "industry": "Capital Goods", "isin": "INE212H01026"},
        {"ticker": "APLAPOLLO.NS", "name": "APL Apollo Tubes Ltd.", "industry": "Capital Goods", "isin": "INE702C01027"},
        {"ticker": "AUBANK.NS", "name": "AU Small Finance Bank Ltd.", "industry": "Financial Services", "isin": "INE949L01017"},
        {"ticker": "AWL.NS", "name": "AWL Agri Business Ltd.", "industry": "Fast Moving Consumer Goods", "isin": "INE699H01024"},
        {"ticker": "ABBOTINDIA.NS", "name": "Abbott India Ltd.", "industry": "Healthcare", "isin": "INE358A01014"},
        {"ticker": "ATGL.NS", "name": "Adani Total Gas Ltd.", "industry": "Oil Gas & Consumable Fuels", "isin": "INE399L01023"},
        {"ticker": "ABCAPITAL.NS", "name": "Aditya Birla Capital Ltd.", "industry": "Financial Services", "isin": "INE674K01013"},
        {"ticker": "AJANTPHARM.NS", "name": "Ajanta Pharmaceuticals Ltd.", "industry": "Healthcare", "isin": "INE031B01049"},
        {"ticker": "ALKEM.NS", "name": "Alkem Laboratories Ltd.", "industry": "Healthcare", "isin": "INE540L01014"},
        {"ticker": "ANTHEM.NS", "name": "Anthem Biosciences Ltd.", "industry": "Healthcare", "isin": "INE0CZ201020"},
        {"ticker": "APARINDS.NS", "name": "Apar Industries Ltd.", "industry": "Capital Goods", "isin": "INE372A01015"},
        {"ticker": "APOLLOTYRE.NS", "name": "Apollo Tyres Ltd.", "industry": "Automobile and Auto Components", "isin": "INE438A01022"},
        {"ticker": "ASHOKLEY.NS", "name": "Ashok Leyland Ltd.", "industry": "Capital Goods", "isin": "INE208A01029"},
        {"ticker": "ASTRAL.NS", "name": "Astral Ltd.", "industry": "Capital Goods", "isin": "INE006I01046"},
        {"ticker": "AUROPHARMA.NS", "name": "Aurobindo Pharma Ltd.", "industry": "Healthcare", "isin": "INE406A01037"},
        {"ticker": "AIIL.NS", "name": "Authum Investment & Infrastructure Ltd.", "industry": "Financial Services", "isin": "INE206F01022"},
        {"ticker": "BSE.NS", "name": "BSE Ltd.", "industry": "Financial Services", "isin": "INE118H01025"},
        {"ticker": "BAJAJHFL.NS", "name": "Bajaj Housing Finance Ltd.", "industry": "Financial Services", "isin": "INE377Y01014"},
        {"ticker": "BALKRISIND.NS", "name": "Balkrishna Industries Ltd.", "industry": "Automobile and Auto Components", "isin": "INE787D01026"},
        {"ticker": "BANKINDIA.NS", "name": "Bank of India", "industry": "Financial Services", "isin": "INE084A01016"},
        {"ticker": "MAHABANK.NS", "name": "Bank of Maharashtra", "industry": "Financial Services", "isin": "INE457A01014"},
        {"ticker": "BERGEPAINT.NS", "name": "Berger Paints India Ltd.", "industry": "Consumer Durables", "isin": "INE463A01038"},
        {"ticker": "BDL.NS", "name": "Bharat Dynamics Ltd.", "industry": "Capital Goods", "isin": "INE171Z01026"},
        {"ticker": "BHARATFORG.NS", "name": "Bharat Forge Ltd.", "industry": "Automobile and Auto Components", "isin": "INE465A01025"},
        {"ticker": "BHEL.NS", "name": "Bharat Heavy Electricals Ltd.", "industry": "Capital Goods", "isin": "INE257A01026"},
        {"ticker": "BHARTIHEXA.NS", "name": "Bharti Hexacom Ltd.", "industry": "Telecommunication", "isin": "INE343G01021"},
        {"ticker": "GROWW.NS", "name": "Billionbrains Garage Ventures Ltd.", "industry": "Financial Services", "isin": "INE0HOQ01053"},
        {"ticker": "BIOCON.NS", "name": "Biocon Ltd.", "industry": "Healthcare", "isin": "INE376G01013"},
        {"ticker": "BLUESTARCO.NS", "name": "Blue Star Ltd.", "industry": "Consumer Durables", "isin": "INE472A01039"},
        {"ticker": "CRISIL.NS", "name": "CRISIL Ltd.", "industry": "Financial Services", "isin": "INE007A01025"},
        {"ticker": "COCHINSHIP.NS", "name": "Cochin Shipyard Ltd.", "industry": "Capital Goods", "isin": "INE704P01025"},
        {"ticker": "COFORGE.NS", "name": "Coforge Ltd.", "industry": "Information Technology", "isin": "INE591G01025"},
        {"ticker": "COLPAL.NS", "name": "Colgate Palmolive (India) Ltd.", "industry": "Fast Moving Consumer Goods", "isin": "INE259A01022"},
        {"ticker": "CONCOR.NS", "name": "Container Corporation of India Ltd.", "industry": "Services", "isin": "INE111A01025"},
        {"ticker": "COROMANDEL.NS", "name": "Coromandel International Ltd.", "industry": "Chemicals", "isin": "INE169A01031"},
        {"ticker": "DABUR.NS", "name": "Dabur India Ltd.", "industry": "Fast Moving Consumer Goods", "isin": "INE016A01026"},
        {"ticker": "DALBHARAT.NS", "name": "Dalmia Bharat Ltd.", "industry": "Construction Materials", "isin": "INE00R701025"},
        {"ticker": "DIXON.NS", "name": "Dixon Technologies (India) Ltd.", "industry": "Consumer Durables", "isin": "INE935N01020"},
        {"ticker": "ENDURANCE.NS", "name": "Endurance Technologies Ltd.", "industry": "Automobile and Auto Components", "isin": "INE913H01037"},
        {"ticker": "ESCORTS.NS", "name": "Escorts Kubota Ltd.", "industry": "Capital Goods", "isin": "INE042A01014"},
        {"ticker": "EXIDEIND.NS", "name": "Exide Industries Ltd.", "industry": "Automobile and Auto Components", "isin": "INE302A01020"},
        {"ticker": "NYKAA.NS", "name": "FSN E-Commerce Ventures Ltd.", "industry": "Consumer Services", "isin": "INE388Y01029"},
        {"ticker": "FEDERALBNK.NS", "name": "Federal Bank Ltd.", "industry": "Financial Services", "isin": "INE171A01029"},
        {"ticker": "FORTIS.NS", "name": "Fortis Healthcare Ltd.", "industry": "Healthcare", "isin": "INE061F01013"},
        {"ticker": "GVT&D.NS", "name": "GE Vernova T&D India Ltd.", "industry": "Capital Goods", "isin": "INE200A01026"},
        {"ticker": "GMRAIRPORT.NS", "name": "GMR Airports Ltd.", "industry": "Services", "isin": "INE776C01039"},
        {"ticker": "GICRE.NS", "name": "General Insurance Corporation of India", "industry": "Financial Services", "isin": "INE481Y01014"},
        {"ticker": "GLAXO.NS", "name": "Glaxosmithkline Pharmaceuticals Ltd.", "industry": "Healthcare", "isin": "INE159A01016"},
        {"ticker": "GLENMARK.NS", "name": "Glenmark Pharmaceuticals Ltd.", "industry": "Healthcare", "isin": "INE935A01035"},
        {"ticker": "MEDANTA.NS", "name": "Global Health Ltd.", "industry": "Healthcare", "isin": "INE474Q01031"},
        {"ticker": "GODFRYPHLP.NS", "name": "Godfrey Phillips India Ltd.", "industry": "Fast Moving Consumer Goods", "isin": "INE260B01028"},
        {"ticker": "GODREJIND.NS", "name": "Godrej Industries Ltd.", "industry": "Diversified", "isin": "INE233A01035"},
        {"ticker": "GODREJPROP.NS", "name": "Godrej Properties Ltd.", "industry": "Realty", "isin": "INE484J01027"},
        {"ticker": "FLUOROCHEM.NS", "name": "Gujarat Fluorochemicals Ltd.", "industry": "Chemicals", "isin": "INE09N301011"},
        {"ticker": "HDBFS.NS", "name": "HDB Financial Services Ltd.", "industry": "Financial Services", "isin": "INE756I01012"},
        {"ticker": "HAVELLS.NS", "name": "Havells India Ltd.", "industry": "Consumer Durables", "isin": "INE176B01034"},
        {"ticker": "HEROMOTOCO.NS", "name": "Hero MotoCorp Ltd.", "industry": "Automobile and Auto Components", "isin": "INE158A01026"},
        {"ticker": "HEXT.NS", "name": "Hexaware Technologies Ltd.", "industry": "Information Technology", "isin": "INE093A01041"},
        {"ticker": "HINDPETRO.NS", "name": "Hindustan Petroleum Corporation Ltd.", "industry": "Oil Gas & Consumable Fuels", "isin": "INE094A01015"},
        {"ticker": "POWERINDIA.NS", "name": "Hitachi Energy India Ltd.", "industry": "Capital Goods", "isin": "INE07Y701011"},
        {"ticker": "HONAUT.NS", "name": "Honeywell Automation India Ltd.", "industry": "Capital Goods", "isin": "INE671A01010"},
        {"ticker": "HUDCO.NS", "name": "Housing & Urban Development Corporation Ltd.", "industry": "Financial Services", "isin": "INE031A01017"},
        {"ticker": "ICICIGI.NS", "name": "ICICI Lombard General Insurance Company Ltd.", "industry": "Financial Services", "isin": "INE765G01017"},
        {"ticker": "ICICIAMC.NS", "name": "ICICI Prudential Asset Management Company Ltd.", "industry": "Financial Services", "isin": "INE346A01027"},
        {"ticker": "ICICIPRULI.NS", "name": "ICICI Prudential Life Insurance Company Ltd.", "industry": "Financial Services", "isin": "INE726G01019"},
        {"ticker": "IDFCFIRSTB.NS", "name": "IDFC First Bank Ltd.", "industry": "Financial Services", "isin": "INE092T01019"},
        {"ticker": "ITCHOTELS.NS", "name": "ITC Hotels Ltd.", "industry": "Consumer Services", "isin": "INE379A01028"},
        {"ticker": "INDIANB.NS", "name": "Indian Bank", "industry": "Financial Services", "isin": "INE562A01011"},
        {"ticker": "IRCTC.NS", "name": "Indian Railway Catering And Tourism Corporation Ltd.", "industry": "Consumer Services", "isin": "INE335Y01020"},
        {"ticker": "IREDA.NS", "name": "Indian Renewable Energy Development Agency Ltd.", "industry": "Financial Services", "isin": "INE202E01016"},
        {"ticker": "INDUSTOWER.NS", "name": "Indus Towers Ltd.", "industry": "Telecommunication", "isin": "INE121J01017"},
        {"ticker": "INDUSINDBK.NS", "name": "IndusInd Bank Ltd.", "industry": "Financial Services", "isin": "INE095A01012"},
        {"ticker": "NAUKRI.NS", "name": "Info Edge (India) Ltd.", "industry": "Consumer Services", "isin": "INE663F01032"},
        {"ticker": "IPCALAB.NS", "name": "Ipca Laboratories Ltd.", "industry": "Healthcare", "isin": "INE571A01038"},
        {"ticker": "JKCEMENT.NS", "name": "J.K. Cement Ltd.", "industry": "Construction Materials", "isin": "INE823G01014"},
        {"ticker": "JSWENERGY.NS", "name": "JSW Energy Ltd.", "industry": "Power", "isin": "INE121E01018"},
        {"ticker": "JSWINFRA.NS", "name": "JSW Infrastructure Ltd.", "industry": "Services", "isin": "INE880J01026"},
        {"ticker": "JSL.NS", "name": "Jindal Stainless Ltd.", "industry": "Metals & Mining", "isin": "INE220G01021"},
        {"ticker": "JUBLFOOD.NS", "name": "Jubilant Foodworks Ltd.", "industry": "Consumer Services", "isin": "INE797F01020"},
        {"ticker": "KPRMILL.NS", "name": "K.P.R. Mill Ltd.", "industry": "Textiles", "isin": "INE930H01031"},
        {"ticker": "KEI.NS", "name": "KEI Industries Ltd.", "industry": "Capital Goods", "isin": "INE878B01027"},
        {"ticker": "KPITTECH.NS", "name": "KPIT Technologies Ltd.", "industry": "Information Technology", "isin": "INE04I401011"},
        {"ticker": "KALYANKJIL.NS", "name": "Kalyan Jewellers India Ltd.", "industry": "Consumer Durables", "isin": "INE303R01014"},
        {"ticker": "LTF.NS", "name": "L&T Finance Ltd.", "industry": "Financial Services", "isin": "INE498L01015"},
        {"ticker": "LTTS.NS", "name": "L&T Technology Services Ltd.", "industry": "Information Technology", "isin": "INE010V01017"},
        {"ticker": "LGEINDIA.NS", "name": "LG Electronics India Ltd.", "industry": "Consumer Durables", "isin": "INE324D01010"},
        {"ticker": "LICHSGFIN.NS", "name": "LIC Housing Finance Ltd.", "industry": "Financial Services", "isin": "INE115A01026"},
        {"ticker": "LAURUSLABS.NS", "name": "Laurus Labs Ltd.", "industry": "Healthcare", "isin": "INE947Q01028"},
        {"ticker": "LENSKART.NS", "name": "Lenskart Solutions Ltd.", "industry": "Consumer Services", "isin": "INE956O01016"},
        {"ticker": "LICI.NS", "name": "Life Insurance Corporation of India", "industry": "Financial Services", "isin": "INE0J1Y01017"},
        {"ticker": "LINDEINDIA.NS", "name": "Linde India Ltd.", "industry": "Chemicals", "isin": "INE473A01011"},
        {"ticker": "LLOYDSME.NS", "name": "Lloyds Metals And Energy Ltd.", "industry": "Metals & Mining", "isin": "INE281B01032"},
        {"ticker": "LUPIN.NS", "name": "Lupin Ltd.", "industry": "Healthcare", "isin": "INE326A01037"},
        {"ticker": "MRF.NS", "name": "MRF Ltd.", "industry": "Automobile and Auto Components", "isin": "INE883A01011"},
        {"ticker": "M&MFIN.NS", "name": "Mahindra & Mahindra Financial Services Ltd.", "industry": "Financial Services", "isin": "INE774D01024"},
        {"ticker": "MANKIND.NS", "name": "Mankind Pharma Ltd.", "industry": "Healthcare", "isin": "INE634S01028"},
        {"ticker": "MARICO.NS", "name": "Marico Ltd.", "industry": "Fast Moving Consumer Goods", "isin": "INE196A01026"},
        {"ticker": "MFSL.NS", "name": "Max Financial Services Ltd.", "industry": "Financial Services", "isin": "INE180A01020"},
        {"ticker": "MOTILALOFS.NS", "name": "Motilal Oswal Financial Services Ltd.", "industry": "Financial Services", "isin": "INE338I01027"},
        {"ticker": "MPHASIS.NS", "name": "MphasiS Ltd.", "industry": "Information Technology", "isin": "INE356A01018"},
        {"ticker": "MCX.NS", "name": "Multi Commodity Exchange of India Ltd.", "industry": "Financial Services", "isin": "INE745G01043"},
        {"ticker": "NHPC.NS", "name": "NHPC Ltd.", "industry": "Power", "isin": "INE848E01016"},
        {"ticker": "NLCINDIA.NS", "name": "NLC India Ltd.", "industry": "Power", "isin": "INE589A01014"},
        {"ticker": "NMDC.NS", "name": "NMDC Ltd.", "industry": "Metals & Mining", "isin": "INE584A01023"},
        {"ticker": "NTPCGREEN.NS", "name": "NTPC Green Energy Ltd.", "industry": "Power", "isin": "INE0ONG01011"},
        {"ticker": "NATIONALUM.NS", "name": "National Aluminium Co. Ltd.", "industry": "Metals & Mining", "isin": "INE139A01034"},
        {"ticker": "NAM-INDIA.NS", "name": "Nippon Life India Asset Management Ltd.", "industry": "Financial Services", "isin": "INE298J01013"},
        {"ticker": "OBEROIRLTY.NS", "name": "Oberoi Realty Ltd.", "industry": "Realty", "isin": "INE093I01010"},
        {"ticker": "OIL.NS", "name": "Oil India Ltd.", "industry": "Oil Gas & Consumable Fuels", "isin": "INE274J01014"},
        {"ticker": "PAYTM.NS", "name": "One 97 Communications Ltd.", "industry": "Financial Services", "isin": "INE982J01020"},
        {"ticker": "OFSS.NS", "name": "Oracle Financial Services Software Ltd.", "industry": "Information Technology", "isin": "INE881D01027"},
        {"ticker": "POLICYBZR.NS", "name": "PB Fintech Ltd.", "industry": "Financial Services", "isin": "INE417T01026"},
        {"ticker": "PIIND.NS", "name": "PI Industries Ltd.", "industry": "Chemicals", "isin": "INE603J01030"},
        {"ticker": "PAGEIND.NS", "name": "Page Industries Ltd.", "industry": "Textiles", "isin": "INE761H01022"},
        {"ticker": "PATANJALI.NS", "name": "Patanjali Foods Ltd.", "industry": "Fast Moving Consumer Goods", "isin": "INE619A01035"},
        {"ticker": "PERSISTENT.NS", "name": "Persistent Systems Ltd.", "industry": "Information Technology", "isin": "INE262H01021"},
        {"ticker": "PETRONET.NS", "name": "Petronet LNG Ltd.", "industry": "Oil Gas & Consumable Fuels", "isin": "INE347G01014"},
        {"ticker": "PHOENIXLTD.NS", "name": "Phoenix Mills Ltd.", "industry": "Realty", "isin": "INE211B01039"},
        {"ticker": "POLYCAB.NS", "name": "Polycab India Ltd.", "industry": "Capital Goods", "isin": "INE455K01017"},
        {"ticker": "PREMIERENE.NS", "name": "Premier Energies Ltd.", "industry": "Capital Goods", "isin": "INE0BS701011"},
        {"ticker": "PRESTIGE.NS", "name": "Prestige Estates Projects Ltd.", "industry": "Realty", "isin": "INE811K01011"},
        {"ticker": "RADICO.NS", "name": "Radico Khaitan Ltd", "industry": "Fast Moving Consumer Goods", "isin": "INE944F01028"},
        {"ticker": "RVNL.NS", "name": "Rail Vikas Nigam Ltd.", "industry": "Construction", "isin": "INE415G01027"},
        {"ticker": "SBICARD.NS", "name": "SBI Cards and Payment Services Ltd.", "industry": "Financial Services", "isin": "INE018E01016"},
        {"ticker": "SJVN.NS", "name": "SJVN Ltd.", "industry": "Power", "isin": "INE002L01015"},
        {"ticker": "SRF.NS", "name": "SRF Ltd.", "industry": "Chemicals", "isin": "INE647A01010"},
        {"ticker": "SCHAEFFLER.NS", "name": "Schaeffler India Ltd.", "industry": "Automobile and Auto Components", "isin": "INE513A01022"},
        {"ticker": "SAIL.NS", "name": "Steel Authority of India Ltd.", "industry": "Metals & Mining", "isin": "INE114A01011"},
        {"ticker": "SUNDARMFIN.NS", "name": "Sundaram Finance Ltd.", "industry": "Financial Services", "isin": "INE660A01013"},
        {"ticker": "SUPREMEIND.NS", "name": "Supreme Industries Ltd.", "industry": "Capital Goods", "isin": "INE195A01028"},
        {"ticker": "SUZLON.NS", "name": "Suzlon Energy Ltd.", "industry": "Capital Goods", "isin": "INE040H01021"},
        {"ticker": "SWIGGY.NS", "name": "Swiggy Ltd.", "industry": "Consumer Services", "isin": "INE00H001014"},
        {"ticker": "TATACOMM.NS", "name": "Tata Communications Ltd.", "industry": "Telecommunication", "isin": "INE151A01013"},
        {"ticker": "TATAELXSI.NS", "name": "Tata Elxsi Ltd.", "industry": "Information Technology", "isin": "INE670A01012"},
        {"ticker": "TATAINVEST.NS", "name": "Tata Investment Corporation Ltd.", "industry": "Financial Services", "isin": "INE672A01026"},
        {"ticker": "NIACL.NS", "name": "The New India Assurance Company Ltd.", "industry": "Financial Services", "isin": "INE470Y01017"},
        {"ticker": "THERMAX.NS", "name": "Thermax Ltd.", "industry": "Capital Goods", "isin": "INE152A01029"},
        {"ticker": "TORNTPOWER.NS", "name": "Torrent Power Ltd.", "industry": "Power", "isin": "INE813H01021"},
        {"ticker": "TIINDIA.NS", "name": "Tube Investments of India Ltd.", "industry": "Automobile and Auto Components", "isin": "INE974X01010"},
        {"ticker": "UNOMINDA.NS", "name": "UNO Minda Ltd.", "industry": "Automobile and Auto Components", "isin": "INE405E01023"},
        {"ticker": "UPL.NS", "name": "UPL Ltd.", "industry": "Chemicals", "isin": "INE628A01036"},
        {"ticker": "UBL.NS", "name": "United Breweries Ltd.", "industry": "Fast Moving Consumer Goods", "isin": "INE686F01025"},
        {"ticker": "VMM.NS", "name": "Vishal Mega Mart Ltd.", "industry": "Consumer Services", "isin": "INE01EA01019"},
        {"ticker": "IDEA.NS", "name": "Vodafone Idea Ltd.", "industry": "Telecommunication", "isin": "INE669E01016"},
        {"ticker": "VOLTAS.NS", "name": "Voltas Ltd.", "industry": "Consumer Durables", "isin": "INE226A01021"},
        {"ticker": "WAAREEENER.NS", "name": "Waaree Energies Ltd.", "industry": "Capital Goods", "isin": "INE377N01017"},
        {"ticker": "YESBANK.NS", "name": "Yes Bank Ltd.", "industry": "Financial Services", "isin": "INE528G01035"},
    ],
    "NIFTYSMALLCAP250": [
        {"ticker": "ACMESOLAR.NS", "name": "ACME Solar Holdings Ltd.", "industry": "Power", "isin": "INE622W01025"},
        {"ticker": "AADHARHFC.NS", "name": "Aadhar Housing Finance Ltd.", "industry": "Financial Services", "isin": "INE883F01010"},
        {"ticker": "AARTIIND.NS", "name": "Aarti Industries Ltd.", "industry": "Chemicals", "isin": "INE769A01020"},
        {"ticker": "AAVAS.NS", "name": "Aavas Financiers Ltd.", "industry": "Financial Services", "isin": "INE216P01012"},
        {"ticker": "ACE.NS", "name": "Action Construction Equipment Ltd.", "industry": "Capital Goods", "isin": "INE731H01025"},
        {"ticker": "ACUTAAS.NS", "name": "Acutaas Chemicals Ltd.", "industry": "Healthcare", "isin": "INE00FF01025"},
        {"ticker": "ABFRL.NS", "name": "Aditya Birla Fashion and Retail Ltd.", "industry": "Consumer Services", "isin": "INE647O01011"},
        {"ticker": "ABLBL.NS", "name": "Aditya Birla Lifestyle Brands Ltd.", "industry": "Consumer Services", "isin": "INE14LE01019"},
        {"ticker": "ABREL.NS", "name": "Aditya Birla Real Estate Ltd.", "industry": "Realty", "isin": "INE055A01016"},
        {"ticker": "ABSLAMC.NS", "name": "Aditya Birla Sun Life AMC Ltd.", "industry": "Financial Services", "isin": "INE404A01024"},
        {"ticker": "CPPLUS.NS", "name": "Aditya Infotech Ltd.", "industry": "Capital Goods", "isin": "INE819V01029"},
        {"ticker": "AEGISLOG.NS", "name": "Aegis Logistics Ltd.", "industry": "Oil Gas & Consumable Fuels", "isin": "INE208C01025"},
        {"ticker": "AEGISVOPAK.NS", "name": "Aegis Vopak Terminals Ltd.", "industry": "Oil Gas & Consumable Fuels", "isin": "INE0INX01018"},
        {"ticker": "AFCONS.NS", "name": "Afcons Infrastructure Ltd.", "industry": "Construction", "isin": "INE101I01011"},
        {"ticker": "AFFLE.NS", "name": "Affle 3i Ltd.", "industry": "Information Technology", "isin": "INE00WC01027"},
        {"ticker": "ABDL.NS", "name": "Allied Blenders and Distillers Ltd.", "industry": "Fast Moving Consumer Goods", "isin": "INE552Z01027"},
        {"ticker": "ARE&M.NS", "name": "Amara Raja Energy & Mobility Ltd.", "industry": "Automobile and Auto Components", "isin": "INE885A01032"},
        {"ticker": "AMBER.NS", "name": "Amber Enterprises India Ltd.", "industry": "Consumer Durables", "isin": "INE371P01015"},
        {"ticker": "ANANDRATHI.NS", "name": "Anand Rathi Wealth Ltd.", "industry": "Financial Services", "isin": "INE463V01026"},
        {"ticker": "ANANTRAJ.NS", "name": "Anant Raj Ltd.", "industry": "Realty", "isin": "INE242C01024"},
        {"ticker": "ANGELONE.NS", "name": "Angel One Ltd.", "industry": "Financial Services", "isin": "INE732I01021"},
        {"ticker": "ANURAS.NS", "name": "Anupam Rasayan India Ltd.", "industry": "Chemicals", "isin": "INE930P01018"},
        {"ticker": "APTUS.NS", "name": "Aptus Value Housing Finance India Ltd.", "industry": "Financial Services", "isin": "INE852O01025"},
        {"ticker": "ASAHIINDIA.NS", "name": "Asahi India Glass Ltd.", "industry": "Automobile and Auto Components", "isin": "INE439A01020"},
        {"ticker": "ASTERDM.NS", "name": "Aster DM Healthcare Ltd.", "industry": "Healthcare", "isin": "INE914M01019"},
        {"ticker": "ATHERENERG.NS", "name": "Ather Energy Ltd.", "industry": "Automobile and Auto Components", "isin": "INE0LEZ01016"},
        {"ticker": "ATUL.NS", "name": "Atul Ltd.", "industry": "Chemicals", "isin": "INE100A01010"},
        {"ticker": "BEML.NS", "name": "BEML Ltd.", "industry": "Capital Goods", "isin": "INE258A01024"},
        {"ticker": "BLS.NS", "name": "BLS International Services Ltd.", "industry": "Consumer Services", "isin": "INE153T01027"},
        {"ticker": "BALRAMCHIN.NS", "name": "Balrampur Chini Mills Ltd.", "industry": "Fast Moving Consumer Goods", "isin": "INE119A01028"},
        {"ticker": "BANDHANBNK.NS", "name": "Bandhan Bank Ltd.", "industry": "Financial Services", "isin": "INE545U01014"},
        {"ticker": "BATAINDIA.NS", "name": "Bata India Ltd.", "industry": "Consumer Durables", "isin": "INE176A01028"},
        {"ticker": "BAYERCROP.NS", "name": "Bayer Cropscience Ltd.", "industry": "Chemicals", "isin": "INE462A01022"},
        {"ticker": "BELRISE.NS", "name": "Belrise Industries Ltd.", "industry": "Automobile and Auto Components", "isin": "INE894V01022"},
        {"ticker": "BIKAJI.NS", "name": "Bikaji Foods International Ltd.", "industry": "Fast Moving Consumer Goods", "isin": "INE00E101023"},
        {"ticker": "BSOFT.NS", "name": "Birlasoft Ltd.", "industry": "Information Technology", "isin": "INE836A01035"},
        {"ticker": "BLUEDART.NS", "name": "Blue Dart Express Ltd.", "industry": "Services", "isin": "INE233B01017"},
        {"ticker": "BLUEJET.NS", "name": "Blue Jet Healthcare Ltd.", "industry": "Healthcare", "isin": "INE0KBH01020"},
        {"ticker": "BBTC.NS", "name": "Bombay Burmah Trading Corporation Ltd.", "industry": "Fast Moving Consumer Goods", "isin": "INE050A01025"},
        {"ticker": "FIRSTCRY.NS", "name": "Brainbees Solutions Ltd.", "industry": "Consumer Services", "isin": "INE02RE01045"},
        {"ticker": "BRIGADE.NS", "name": "Brigade Enterprises Ltd.", "industry": "Realty", "isin": "INE791I01019"},
        {"ticker": "MAPMYINDIA.NS", "name": "C.E. Info Systems Ltd.", "industry": "Information Technology", "isin": "INE0BV301023"},
        {"ticker": "CCL.NS", "name": "CCL Products (I) Ltd.", "industry": "Fast Moving Consumer Goods", "isin": "INE421D01022"},
        {"ticker": "CESC.NS", "name": "CESC Ltd.", "industry": "Power", "isin": "INE486A01021"},
        {"ticker": "CIEINDIA.NS", "name": "CIE Automotive India Ltd.", "industry": "Automobile and Auto Components", "isin": "INE536H01010"},
        {"ticker": "CANFINHOME.NS", "name": "Can Fin Homes Ltd.", "industry": "Financial Services", "isin": "INE477A01020"},
        {"ticker": "CANHLIFE.NS", "name": "Canara HSBC Life Insurance Company Ltd.", "industry": "Financial Services", "isin": "INE01TY01017"},
        {"ticker": "CAPLIPOINT.NS", "name": "Caplin Point Laboratories Ltd.", "industry": "Healthcare", "isin": "INE475E01026"},
        {"ticker": "CGCL.NS", "name": "Capri Global Capital Ltd.", "industry": "Financial Services", "isin": "INE180C01042"},
        {"ticker": "CARBORUNIV.NS", "name": "Carborundum Universal Ltd.", "industry": "Capital Goods", "isin": "INE120A01034"},
        {"ticker": "CARTRADE.NS", "name": "Cartrade Tech Ltd.", "industry": "Consumer Services", "isin": "INE290S01011"},
        {"ticker": "CASTROLIND.NS", "name": "Castrol India Ltd.", "industry": "Oil Gas & Consumable Fuels", "isin": "INE172A01027"},
        {"ticker": "CEATLTD.NS", "name": "Ceat Ltd.", "industry": "Automobile and Auto Components", "isin": "INE482A01020"},
        {"ticker": "CEMPRO.NS", "name": "Cemindia Projects Ltd.", "industry": "Construction", "isin": "INE686A01026"},
        {"ticker": "CENTRALBK.NS", "name": "Central Bank of India", "industry": "Financial Services", "isin": "INE483A01010"},
        {"ticker": "CDSL.NS", "name": "Central Depository Services (India) Ltd.", "industry": "Financial Services", "isin": "INE736A01011"},
        {"ticker": "CHALET.NS", "name": "Chalet Hotels Ltd.", "industry": "Consumer Services", "isin": "INE427F01016"},
        {"ticker": "CHAMBLFERT.NS", "name": "Chambal Fertilizers & Chemicals Ltd.", "industry": "Chemicals", "isin": "INE085A01013"},
        {"ticker": "CHENNPETRO.NS", "name": "Chennai Petroleum Corporation Ltd.", "industry": "Oil Gas & Consumable Fuels", "isin": "INE178A01016"},
        {"ticker": "CHOICEIN.NS", "name": "Choice International Ltd.", "industry": "Financial Services", "isin": "INE102B01014"},
        {"ticker": "CHOLAHLDNG.NS", "name": "Cholamandalam Financial Holdings Ltd.", "industry": "Financial Services", "isin": "INE149A01033"},
        {"ticker": "CUB.NS", "name": "City Union Bank Ltd.", "industry": "Financial Services", "isin": "INE491A01021"},
        {"ticker": "CLEAN.NS", "name": "Clean Science and Technology Ltd.", "industry": "Chemicals", "isin": "INE227W01023"},
        {"ticker": "COHANCE.NS", "name": "Cohance Lifesciences Ltd.", "industry": "Healthcare", "isin": "INE03QK01018"},
        {"ticker": "CAMS.NS", "name": "Computer Age Management Services Ltd.", "industry": "Financial Services", "isin": "INE596I01020"},
        {"ticker": "CONCORDBIO.NS", "name": "Concord Biotech Ltd.", "industry": "Healthcare", "isin": "INE338H01029"},
        {"ticker": "CRAFTSMAN.NS", "name": "Craftsman Automation Ltd.", "industry": "Automobile and Auto Components", "isin": "INE00LO01017"},
        {"ticker": "CREDITACC.NS", "name": "CreditAccess Grameen Ltd.", "industry": "Financial Services", "isin": "INE741K01010"},
        {"ticker": "CROMPTON.NS", "name": "Crompton Greaves Consumer Electricals Ltd.", "industry": "Consumer Durables", "isin": "INE299U01018"},
        {"ticker": "CYIENT.NS", "name": "Cyient Ltd.", "industry": "Information Technology", "isin": "INE136B01020"},
        {"ticker": "DCMSHRIRAM.NS", "name": "DCM Shriram Ltd.", "industry": "Diversified", "isin": "INE499A01024"},
        {"ticker": "DATAPATTNS.NS", "name": "Data Patterns (India) Ltd.", "industry": "Capital Goods", "isin": "INE0IX101010"},
        {"ticker": "DOMS.NS", "name": "DOMS Industries Ltd.", "industry": "Fast Moving Consumer Goods", "isin": "INE321T01012"},
        {"ticker": "DEEPAKFERT.NS", "name": "Deepak Fertilisers & Petrochemicals Corp. Ltd.", "industry": "Chemicals", "isin": "INE501A01019"},
        {"ticker": "DEEPAKNTR.NS", "name": "Deepak Nitrite Ltd.", "industry": "Chemicals", "isin": "INE288B01029"},
        {"ticker": "DELHIVERY.NS", "name": "Delhivery Ltd.", "industry": "Services", "isin": "INE148O01028"},
        {"ticker": "DEVYANI.NS", "name": "Devyani International Ltd.", "industry": "Consumer Services", "isin": "INE872J01023"},
        {"ticker": "LALPATHLAB.NS", "name": "Dr. Lal Path Labs Ltd.", "industry": "Healthcare", "isin": "INE600L01024"},
        {"ticker": "EIDPARRY.NS", "name": "E.I.D. Parry (India) Ltd.", "industry": "Fast Moving Consumer Goods", "isin": "INE126A01031"},
        {"ticker": "EIHOTEL.NS", "name": "EIH Ltd.", "industry": "Consumer Services", "isin": "INE230A01023"},
        {"ticker": "ELECON.NS", "name": "Elecon Engineering Co. Ltd.", "industry": "Capital Goods", "isin": "INE205B01031"},
        {"ticker": "ELGIEQUIP.NS", "name": "Elgi Equipments Ltd.", "industry": "Capital Goods", "isin": "INE285A01027"},
        {"ticker": "EMAMILTD.NS", "name": "Emami Ltd.", "industry": "Fast Moving Consumer Goods", "isin": "INE548C01032"},
        {"ticker": "EMCURE.NS", "name": "Emcure Pharmaceuticals Ltd.", "industry": "Healthcare", "isin": "INE168P01015"},
        {"ticker": "EMMVEE.NS", "name": "Emmvee Photovoltaic Power Ltd.", "industry": "Capital Goods", "isin": "INE1C6T01020"},
        {"ticker": "ENGINERSIN.NS", "name": "Engineers India Ltd.", "industry": "Construction", "isin": "INE510A01028"},
        {"ticker": "ERIS.NS", "name": "Eris Lifesciences Ltd.", "industry": "Healthcare", "isin": "INE406M01024"},
        {"ticker": "FACT.NS", "name": "Fertilisers and Chemicals Travancore Ltd.", "industry": "Chemicals", "isin": "INE188A01015"},
        {"ticker": "FINCABLES.NS", "name": "Finolex Cables Ltd.", "industry": "Capital Goods", "isin": "INE235A01022"},
        {"ticker": "FSL.NS", "name": "Firstsource Solutions Ltd.", "industry": "Services", "isin": "INE684F01012"},
        {"ticker": "FIVESTAR.NS", "name": "Five-Star Business Finance Ltd.", "industry": "Financial Services", "isin": "INE128S01021"},
        {"ticker": "FORCEMOT.NS", "name": "Force Motors Ltd.", "industry": "Automobile and Auto Components", "isin": "INE451A01017"},
        {"ticker": "GABRIEL.NS", "name": "Gabriel India Ltd.", "industry": "Automobile and Auto Components", "isin": "INE524A01029"},
        {"ticker": "GALLANTT.NS", "name": "Gallantt Ispat Ltd.", "industry": "Capital Goods", "isin": "INE297H01019"},
        {"ticker": "GRSE.NS", "name": "Garden Reach Shipbuilders & Engineers Ltd.", "industry": "Capital Goods", "isin": "INE382Z01011"},
        {"ticker": "GILLETTE.NS", "name": "Gillette India Ltd.", "industry": "Fast Moving Consumer Goods", "isin": "INE322A01010"},
        {"ticker": "GLAND.NS", "name": "Gland Pharma Ltd.", "industry": "Healthcare", "isin": "INE068V01023"},
        {"ticker": "GODIGIT.NS", "name": "Go Digit General Insurance Ltd.", "industry": "Financial Services", "isin": "INE03JT01014"},
        {"ticker": "GPIL.NS", "name": "Godawari Power & Ispat Ltd.", "industry": "Capital Goods", "isin": "INE177H01039"},
        {"ticker": "GRANULES.NS", "name": "Granules India Ltd.", "industry": "Healthcare", "isin": "INE101D01020"},
        {"ticker": "GRAPHITE.NS", "name": "Graphite India Ltd.", "industry": "Capital Goods", "isin": "INE371A01025"},
        {"ticker": "GRAVITA.NS", "name": "Gravita India Ltd.", "industry": "Metals & Mining", "isin": "INE024L01027"},
        {"ticker": "GESHIP.NS", "name": "Great Eastern Shipping Co. Ltd.", "industry": "Services", "isin": "INE017A01032"},
        {"ticker": "GMDCLTD.NS", "name": "Gujarat Mineral Development Corporation Ltd.", "industry": "Metals & Mining", "isin": "INE131A01031"},
        {"ticker": "HEG.NS", "name": "H.E.G. Ltd.", "industry": "Capital Goods", "isin": "INE545A01024"},
        {"ticker": "HBLENGINE.NS", "name": "HBL Engineering Ltd.", "industry": "Capital Goods", "isin": "INE292B01021"},
        {"ticker": "HFCL.NS", "name": "HFCL Ltd.", "industry": "Telecommunication", "isin": "INE548A01028"},
        {"ticker": "HSCL.NS", "name": "Himadri Speciality Chemical Ltd.", "industry": "Chemicals", "isin": "INE019C01026"},
        {"ticker": "HINDCOPPER.NS", "name": "Hindustan Copper Ltd.", "industry": "Metals & Mining", "isin": "INE531E01026"},
        {"ticker": "HOMEFIRST.NS", "name": "Home First Finance Company India Ltd.", "industry": "Financial Services", "isin": "INE481N01025"},
        {"ticker": "HONASA.NS", "name": "Honasa Consumer Ltd.", "industry": "Fast Moving Consumer Goods", "isin": "INE0J5401028"},
        {"ticker": "IDBI.NS", "name": "IDBI Bank Ltd.", "industry": "Financial Services", "isin": "INE008A01015"},
        {"ticker": "IFCI.NS", "name": "IFCI Ltd.", "industry": "Financial Services", "isin": "INE039A01010"},
        {"ticker": "IIFL.NS", "name": "IIFL Finance Ltd.", "industry": "Financial Services", "isin": "INE530B01024"},
        {"ticker": "IRB.NS", "name": "IRB Infrastructure Developers Ltd.", "industry": "Construction", "isin": "INE821I01022"},
        {"ticker": "IRCON.NS", "name": "IRCON International Ltd.", "industry": "Construction", "isin": "INE962Y01021"},
        {"ticker": "ITI.NS", "name": "ITI Ltd.", "industry": "Telecommunication", "isin": "INE248A01017"},
        {"ticker": "INDGN.NS", "name": "Indegene Ltd.", "industry": "Healthcare", "isin": "INE065X01017"},
        {"ticker": "INDIACEM.NS", "name": "India Cements Ltd.", "industry": "Construction Materials", "isin": "INE383A01012"},
        {"ticker": "INDIAMART.NS", "name": "Indiamart Intermesh Ltd.", "industry": "Consumer Services", "isin": "INE933S01016"},
        {"ticker": "IEX.NS", "name": "Indian Energy Exchange Ltd.", "industry": "Financial Services", "isin": "INE022Q01020"},
        {"ticker": "IOB.NS", "name": "Indian Overseas Bank", "industry": "Financial Services", "isin": "INE565A01014"},
        {"ticker": "IGL.NS", "name": "Indraprastha Gas Ltd.", "industry": "Oil Gas & Consumable Fuels", "isin": "INE203G01027"},
        {"ticker": "INOXWIND.NS", "name": "Inox Wind Ltd.", "industry": "Capital Goods", "isin": "INE066P01011"},
        {"ticker": "INTELLECT.NS", "name": "Intellect Design Arena Ltd.", "industry": "Information Technology", "isin": "INE306R01017"},
        {"ticker": "IGIL.NS", "name": "International Gemological Institute Ltd.", "industry": "Services", "isin": "INE0Q9301021"},
        {"ticker": "IKS.NS", "name": "Inventurus Knowledge Solutions Ltd.", "industry": "Information Technology", "isin": "INE115Q01022"},
        {"ticker": "JBCHEPHARM.NS", "name": "J.B. Chemicals & Pharmaceuticals Ltd.", "industry": "Healthcare", "isin": "INE572A01036"},
        {"ticker": "JBMA.NS", "name": "JBM Auto Ltd.", "industry": "Automobile and Auto Components", "isin": "INE927D01051"},
        {"ticker": "JKTYRE.NS", "name": "JK Tyre & Industries Ltd.", "industry": "Automobile and Auto Components", "isin": "INE573A01042"},
        {"ticker": "JMFINANCIL.NS", "name": "JM Financial Ltd.", "industry": "Financial Services", "isin": "INE780C01023"},
        {"ticker": "JSWCEMENT.NS", "name": "JSW Cement Ltd.", "industry": "Construction Materials", "isin": "INE718I01012"},
        {"ticker": "JSWDULUX.NS", "name": "JSW Dulux Ltd.", "industry": "Consumer Durables", "isin": "INE133A01011"},
        {"ticker": "JAINREC.NS", "name": "Jain Resource Recycling Ltd.", "industry": "Metals & Mining", "isin": "INE0YD401026"},
        {"ticker": "JPPOWER.NS", "name": "Jaiprakash Power Ventures Ltd.", "industry": "Power", "isin": "INE351F01018"},
        {"ticker": "J&KBANK.NS", "name": "Jammu & Kashmir Bank Ltd.", "industry": "Financial Services", "isin": "INE168A01041"},
        {"ticker": "JINDALSAW.NS", "name": "Jindal Saw Ltd.", "industry": "Capital Goods", "isin": "INE324A01032"},
        {"ticker": "JUBLINGREA.NS", "name": "Jubilant Ingrevia Ltd.", "industry": "Chemicals", "isin": "INE0BY001018"},
        {"ticker": "JUBLPHARMA.NS", "name": "Jubilant Pharmova Ltd.", "industry": "Healthcare", "isin": "INE700A01033"},
        {"ticker": "JWL.NS", "name": "Jupiter Wagons Ltd.", "industry": "Capital Goods", "isin": "INE209L01016"},
        {"ticker": "JYOTICNC.NS", "name": "Jyoti CNC Automation Ltd.", "industry": "Capital Goods", "isin": "INE980O01024"},
        {"ticker": "KAJARIACER.NS", "name": "Kajaria Ceramics Ltd.", "industry": "Consumer Durables", "isin": "INE217B01036"},
        {"ticker": "KPIL.NS", "name": "Kalpataru Projects International Ltd.", "industry": "Construction", "isin": "INE220B01022"},
        {"ticker": "KARURVYSYA.NS", "name": "Karur Vysya Bank Ltd.", "industry": "Financial Services", "isin": "INE036D01028"},
        {"ticker": "KAYNES.NS", "name": "Kaynes Technology India Ltd.", "industry": "Capital Goods", "isin": "INE918Z01012"},
        {"ticker": "KEC.NS", "name": "Kec International Ltd.", "industry": "Construction", "isin": "INE389H01022"},
        {"ticker": "KFINTECH.NS", "name": "Kfin Technologies Ltd.", "industry": "Financial Services", "isin": "INE138Y01010"},
        {"ticker": "KIRLOSENG.NS", "name": "Kirloskar Oil Eng Ltd.", "industry": "Capital Goods", "isin": "INE146L01010"},
        {"ticker": "KIMS.NS", "name": "Krishna Institute of Medical Sciences Ltd.", "industry": "Healthcare", "isin": "INE967H01025"},
        {"ticker": "LTFOODS.NS", "name": "LT Foods Ltd.", "industry": "Fast Moving Consumer Goods", "isin": "INE818H01020"},
        {"ticker": "LATENTVIEW.NS", "name": "Latent View Analytics Ltd.", "industry": "Information Technology", "isin": "INE0I7C01011"},
        {"ticker": "THELEELA.NS", "name": "Leela Palaces Hotels & Resorts Ltd.", "industry": "Consumer Services", "isin": "INE0AQ201015"},
        {"ticker": "LEMONTREE.NS", "name": "Lemon Tree Hotels Ltd.", "industry": "Consumer Services", "isin": "INE970X01018"},
        {"ticker": "MMTC.NS", "name": "MMTC Ltd.", "industry": "Services", "isin": "INE123F01029"},
        {"ticker": "MGL.NS", "name": "Mahanagar Gas Ltd.", "industry": "Oil Gas & Consumable Fuels", "isin": "INE002S01010"},
        {"ticker": "MANAPPURAM.NS", "name": "Manappuram Finance Ltd.", "industry": "Financial Services", "isin": "INE522D01027"},
        {"ticker": "MRPL.NS", "name": "Mangalore Refinery & Petrochemicals Ltd.", "industry": "Oil Gas & Consumable Fuels", "isin": "INE103A01014"},
        {"ticker": "MEESHO.NS", "name": "Meesho Ltd.", "industry": "Consumer Services", "isin": "INE0VDM01015"},
        {"ticker": "MINDACORP.NS", "name": "Minda Corporation Ltd.", "industry": "Automobile and Auto Components", "isin": "INE842C01021"},
        {"ticker": "MSUMI.NS", "name": "Motherson Sumi Wiring India Ltd.", "industry": "Automobile and Auto Components", "isin": "INE0FS801015"},
        {"ticker": "NATCOPHARM.NS", "name": "NATCO Pharma Ltd.", "industry": "Healthcare", "isin": "INE987B01026"},
        {"ticker": "NBCC.NS", "name": "NBCC (India) Ltd.", "industry": "Construction", "isin": "INE095N01031"},
        {"ticker": "NCC.NS", "name": "NCC Ltd.", "industry": "Construction", "isin": "INE868B01028"},
        {"ticker": "NSLNISP.NS", "name": "NMDC Steel Ltd.", "industry": "Metals & Mining", "isin": "INE0NNS01018"},
        {"ticker": "NH.NS", "name": "Narayana Hrudayalaya Ltd.", "industry": "Healthcare", "isin": "INE410P01011"},
        {"ticker": "NAVA.NS", "name": "Nava Ltd.", "industry": "Power", "isin": "INE725A01030"},
        {"ticker": "NAVINFLUOR.NS", "name": "Navin Fluorine International Ltd.", "industry": "Chemicals", "isin": "INE048G01026"},
        {"ticker": "NETWEB.NS", "name": "Netweb Technologies India Ltd.", "industry": "Information Technology", "isin": "INE0NT901020"},
        {"ticker": "NEULANDLAB.NS", "name": "Neuland Laboratories Ltd.", "industry": "Healthcare", "isin": "INE794A01010"},
        {"ticker": "NEWGEN.NS", "name": "Newgen Software Technologies Ltd.", "industry": "Information Technology", "isin": "INE619B01017"},
        {"ticker": "NIVABUPA.NS", "name": "Niva Bupa Health Insurance Company Ltd.", "industry": "Financial Services", "isin": "INE995S01015"},
        {"ticker": "NUVAMA.NS", "name": "Nuvama Wealth Management Ltd.", "industry": "Financial Services", "isin": "INE531F01023"},
        {"ticker": "NUVOCO.NS", "name": "Nuvoco Vistas Corporation Ltd.", "industry": "Construction Materials", "isin": "INE118D01016"},
        {"ticker": "OLAELEC.NS", "name": "Ola Electric Mobility Ltd.", "industry": "Automobile and Auto Components", "isin": "INE0LXG01040"},
        {"ticker": "OLECTRA.NS", "name": "Olectra Greentech Ltd.", "industry": "Automobile and Auto Components", "isin": "INE260D01016"},
        {"ticker": "ONESOURCE.NS", "name": "Onesource Specialty Pharma Ltd.", "industry": "Healthcare", "isin": "INE013P01021"},
        {"ticker": "PCBL.NS", "name": "PCBL Chemical Ltd.", "industry": "Chemicals", "isin": "INE602A01031"},
        {"ticker": "PGEL.NS", "name": "PG Electroplast Ltd.", "industry": "Consumer Durables", "isin": "INE457L01029"},
        {"ticker": "PNBHOUSING.NS", "name": "PNB Housing Finance Ltd.", "industry": "Financial Services", "isin": "INE572E01012"},
        {"ticker": "PTCIL.NS", "name": "PTC Industries Ltd.", "industry": "Capital Goods", "isin": "INE596F01018"},
        {"ticker": "PVRINOX.NS", "name": "PVR INOX Ltd.", "industry": "Media Entertainment & Publication", "isin": "INE191H01014"},
        {"ticker": "PARADEEP.NS", "name": "Paradeep Phosphates Ltd.", "industry": "Chemicals", "isin": "INE088F01024"},
        {"ticker": "PFIZER.NS", "name": "Pfizer Ltd.", "industry": "Healthcare", "isin": "INE182A01018"},
        {"ticker": "PWL.NS", "name": "Physicswallah Ltd.", "industry": "Consumer Services", "isin": "INE0LP301011"},
        {"ticker": "PINELABS.NS", "name": "Pine Labs Ltd.", "industry": "Financial Services", "isin": "INE15B701018"},
        {"ticker": "PIRAMALFIN.NS", "name": "Piramal Finance Ltd.", "industry": "Financial Services", "isin": "INE202B01038"},
        {"ticker": "PPLPHARMA.NS", "name": "Piramal Pharma Ltd.", "industry": "Healthcare", "isin": "INE0DK501011"},
        {"ticker": "POLYMED.NS", "name": "Poly Medicure Ltd.", "industry": "Healthcare", "isin": "INE205C01021"},
        {"ticker": "POONAWALLA.NS", "name": "Poonawalla Fincorp Ltd.", "industry": "Financial Services", "isin": "INE511C01022"},
        {"ticker": "RRKABEL.NS", "name": "R R Kabel Ltd.", "industry": "Capital Goods", "isin": "INE777K01022"},
        {"ticker": "RBLBANK.NS", "name": "RBL Bank Ltd.", "industry": "Financial Services", "isin": "INE976G01028"},
        {"ticker": "RHIM.NS", "name": "RHI MAGNESITA INDIA LTD.", "industry": "Capital Goods", "isin": "INE743M01012"},
        {"ticker": "RITES.NS", "name": "RITES Ltd.", "industry": "Construction", "isin": "INE320J01015"},
        {"ticker": "RAILTEL.NS", "name": "Railtel Corporation Of India Ltd.", "industry": "Telecommunication", "isin": "INE0DD101019"},
        {"ticker": "RAINBOW.NS", "name": "Rainbow Childrens Medicare Ltd.", "industry": "Healthcare", "isin": "INE961O01016"},
        {"ticker": "RKFORGE.NS", "name": "Ramkrishna Forgings Ltd.", "industry": "Automobile and Auto Components", "isin": "INE399G01023"},
        {"ticker": "REDINGTON.NS", "name": "Redington Ltd.", "industry": "Services", "isin": "INE891D01026"},
        {"ticker": "RPOWER.NS", "name": "Reliance Power Ltd.", "industry": "Power", "isin": "INE614G01033"},
        {"ticker": "SBFC.NS", "name": "SBFC Finance Ltd.", "industry": "Financial Services", "isin": "INE423Y01016"},
        {"ticker": "SAGILITY.NS", "name": "Sagility Ltd.", "industry": "Information Technology", "isin": "INE0W2G01015"},
        {"ticker": "SAILIFE.NS", "name": "Sai Life Sciences Ltd.", "industry": "Healthcare", "isin": "INE570L01029"},
        {"ticker": "SAMMAANCAP.NS", "name": "Sammaan Capital Ltd.", "industry": "Financial Services", "isin": "INE148I01020"},
        {"ticker": "SAPPHIRE.NS", "name": "Sapphire Foods India Ltd.", "industry": "Consumer Services", "isin": "INE806T01020"},
        {"ticker": "SARDAEN.NS", "name": "Sarda Energy and Minerals Ltd.", "industry": "Metals & Mining", "isin": "INE385C01021"},
        {"ticker": "SAREGAMA.NS", "name": "Saregama India Ltd", "industry": "Media Entertainment & Publication", "isin": "INE979A01025"},
        {"ticker": "SCHNEIDER.NS", "name": "Schneider Electric Infrastructure Ltd.", "industry": "Capital Goods", "isin": "INE839M01018"},
        {"ticker": "SCI.NS", "name": "Shipping Corporation of India Ltd.", "industry": "Services", "isin": "INE109A01011"},
        {"ticker": "SHYAMMETL.NS", "name": "Shyam Metalics and Energy Ltd.", "industry": "Capital Goods", "isin": "INE810G01011"},
        {"ticker": "SIGNATURE.NS", "name": "Signatureglobal (India) Ltd.", "industry": "Realty", "isin": "INE903U01023"},
        {"ticker": "SOBHA.NS", "name": "Sobha Ltd.", "industry": "Realty", "isin": "INE671H01015"},
        {"ticker": "SONACOMS.NS", "name": "Sona BLW Precision Forgings Ltd.", "industry": "Automobile and Auto Components", "isin": "INE073K01018"},
        {"ticker": "SONATSOFTW.NS", "name": "Sonata Software Ltd.", "industry": "Information Technology", "isin": "INE269A01021"},
        {"ticker": "STARHEALTH.NS", "name": "Star Health and Allied Insurance Company Ltd.", "industry": "Financial Services", "isin": "INE575P01011"},
        {"ticker": "SUMICHEM.NS", "name": "Sumitomo Chemical India Ltd.", "industry": "Chemicals", "isin": "INE258G01013"},
        {"ticker": "SUNTV.NS", "name": "Sun TV Network Ltd.", "industry": "Media Entertainment & Publication", "isin": "INE424H01027"},
        {"ticker": "SPLPETRO.NS", "name": "Supreme Petrochem Ltd.", "industry": "Chemicals", "isin": "INE663A01033"},
        {"ticker": "SWANCORP.NS", "name": "Swan Corp Ltd.", "industry": "Chemicals", "isin": "INE665A01038"},
        {"ticker": "SYNGENE.NS", "name": "Syngene International Ltd.", "industry": "Healthcare", "isin": "INE398R01022"},
        {"ticker": "SYRMA.NS", "name": "Syrma SGS Technology Ltd.", "industry": "Capital Goods", "isin": "INE0DYJ01015"},
        {"ticker": "TBOTEK.NS", "name": "TBO Tek Ltd.", "industry": "Consumer Services", "isin": "INE673O01025"},
        {"ticker": "TATACHEM.NS", "name": "Tata Chemicals Ltd.", "industry": "Chemicals", "isin": "INE092A01019"},
        {"ticker": "TATATECH.NS", "name": "Tata Technologies Ltd.", "industry": "Information Technology", "isin": "INE142M01025"},
        {"ticker": "TTML.NS", "name": "Tata Teleservices (Maharashtra) Ltd.", "industry": "Telecommunication", "isin": "INE517B01013"},
        {"ticker": "TECHNOE.NS", "name": "Techno Electric & Engineering Company Ltd.", "industry": "Construction", "isin": "INE285K01026"},
        {"ticker": "TEGA.NS", "name": "Tega Industries Ltd.", "industry": "Capital Goods", "isin": "INE011K01018"},
        {"ticker": "TEJASNET.NS", "name": "Tejas Networks Ltd.", "industry": "Telecommunication", "isin": "INE010J01012"},
        {"ticker": "TENNIND.NS", "name": "Tenneco Clean Air India Ltd.", "industry": "Automobile and Auto Components", "isin": "INE19RI01016"},
        {"ticker": "RAMCOCEM.NS", "name": "The Ramco Cements Ltd.", "industry": "Construction Materials", "isin": "INE331A01037"},
        {"ticker": "TIMKEN.NS", "name": "Timken India Ltd.", "industry": "Capital Goods", "isin": "INE325A01013"},
        {"ticker": "TITAGARH.NS", "name": "Titagarh Rail Systems Ltd.", "industry": "Capital Goods", "isin": "INE615H01020"},
        {"ticker": "TARIL.NS", "name": "Transformers And Rectifiers (India) Ltd.", "industry": "Capital Goods", "isin": "INE763I01026"},
        {"ticker": "TRAVELFOOD.NS", "name": "Travel Food Services Ltd.", "industry": "Consumer Services", "isin": "INE103V01028"},
        {"ticker": "TRIDENT.NS", "name": "Trident Ltd.", "industry": "Textiles", "isin": "INE064C01022"},
        {"ticker": "TRITURBINE.NS", "name": "Triveni Turbine Ltd.", "industry": "Capital Goods", "isin": "INE152M01016"},
        {"ticker": "UCOBANK.NS", "name": "UCO Bank", "industry": "Financial Services", "isin": "INE691A01018"},
        {"ticker": "UTIAMC.NS", "name": "UTI Asset Management Company Ltd.", "industry": "Financial Services", "isin": "INE094J01016"},
        {"ticker": "URBANCO.NS", "name": "Urban Company Ltd.", "industry": "Consumer Services", "isin": "INE0CAZ01013"},
        {"ticker": "USHAMART.NS", "name": "Usha Martin Ltd.", "industry": "Capital Goods", "isin": "INE228A01035"},
        {"ticker": "VTL.NS", "name": "Vardhman Textiles Ltd.", "industry": "Textiles", "isin": "INE825A01020"},
        {"ticker": "VIJAYA.NS", "name": "Vijaya Diagnostic Centre Ltd.", "industry": "Healthcare", "isin": "INE043W01024"},
        {"ticker": "WELCORP.NS", "name": "Welspun Corp Ltd.", "industry": "Capital Goods", "isin": "INE191B01025"},
        {"ticker": "WELSPUNLIV.NS", "name": "Welspun Living Ltd.", "industry": "Textiles", "isin": "INE192B01031"},
        {"ticker": "WHIRLPOOL.NS", "name": "Whirlpool of India Ltd.", "industry": "Consumer Durables", "isin": "INE716A01013"},
        {"ticker": "WOCKPHARMA.NS", "name": "Wockhardt Ltd.", "industry": "Healthcare", "isin": "INE049B01025"},
        {"ticker": "ZFCVINDIA.NS", "name": "ZF Commercial Vehicle Control Systems India Ltd.", "industry": "Automobile and Auto Components", "isin": "INE342J01019"},
        {"ticker": "ZEEL.NS", "name": "Zee Entertainment Enterprises Ltd.", "industry": "Media Entertainment & Publication", "isin": "INE256A01028"},
        {"ticker": "ZENTEC.NS", "name": "Zen Technologies Ltd.", "industry": "Capital Goods", "isin": "INE251B01027"},
        {"ticker": "ZENSARTECH.NS", "name": "Zensar Technolgies Ltd.", "industry": "Information Technology", "isin": "INE520A01027"},
        {"ticker": "ZYDUSWELL.NS", "name": "Zydus Wellness Ltd.", "industry": "Fast Moving Consumer Goods", "isin": "INE768C01028"},
        {"ticker": "ECLERX.NS", "name": "eClerx Services Ltd.", "industry": "Services", "isin": "INE738I01010"},
    ],
}

# Sectoral-index-only companies outside the Nifty 500 cap-tier universe.
# All sourced from a confirmed direct archives.nseindia.com CSV fetch (not
# a third-party fallback), so treated as trustworthy despite being smaller
# names. index_tier="OTHER" — no cap-tier claim is made for these.
EXTRA_COMPANIES = [
    {"ticker": "PSB.NS", "name": "Punjab & Sind Bank", "industry": "Financial Services", "isin": "INE608A01012"},
    {"ticker": "DBCORP.NS", "name": "D.B.Corp Ltd.", "industry": "Media Entertainment & Publication", "isin": "INE950I01011"},
    {"ticker": "HATHWAY.NS", "name": "Hathway Cable & Datacom Ltd.", "industry": "Media Entertainment & Publication", "isin": "INE982F01036"},
    {"ticker": "NAZARA.NS", "name": "Nazara Technologies Ltd.", "industry": "Media Entertainment & Publication", "isin": "INE418L01047"},
    {"ticker": "NETWORK18.NS", "name": "Network18 Media & Investments Ltd.", "industry": "Media Entertainment & Publication", "isin": "INE870H01013"},
    {"ticker": "PFOCUS.NS", "name": "Prime Focus Ltd.", "industry": "Media Entertainment & Publication", "isin": "INE367G01038"},
    {"ticker": "TIPSMUSIC.NS", "name": "Tips Music Ltd.", "industry": "Media Entertainment & Publication", "isin": "INE716B01029"},
]

# index_code -> bare NSE symbols (no ".NS") belonging to that index.
# Symbols not present in CAP_TIER_COMPANIES/EXTRA_COMPANIES are ignored by
# the loader with a warning (should not happen -- every symbol here was
# cross-checked against the master lists above during data compilation).
INDEX_MEMBERSHIPS = {
    "NIFTY50": [
        "ADANIENT", "ADANIPORTS", "APOLLOHOSP", "ASIANPAINT", "AXISBANK", "BAJAJ-AUTO", "BAJFINANCE",
        "BAJAJFINSV", "BEL", "BHARTIARTL", "CIPLA", "COALINDIA", "DRREDDY", "EICHERMOT", "ETERNAL",
        "GRASIM", "HCLTECH", "HDFCBANK", "HDFCLIFE", "HINDALCO", "HINDUNILVR", "ICICIBANK", "INDIGO",
        "INFY", "ITC", "JIOFIN", "JSWSTEEL", "KOTAKBANK", "LT", "M&M", "MARUTI", "MAXHEALTH", "NESTLEIND",
        "NTPC", "ONGC", "POWERGRID", "RELIANCE", "SBILIFE", "SHRIRAMFIN", "SBIN", "SUNPHARMA", "TCS",
        "TATACONSUM", "TMPV", "TATASTEEL", "TECHM", "TITAN", "TRENT", "ULTRACEMCO", "WIPRO",
    ],
    "NIFTYNEXT50": [
        "ABB", "ADANIENSOL", "ADANIGREEN", "ADANIPOWER", "AMBUJACEM", "DMART", "BAJAJHLDNG", "BANKBARODA",
        "BPCL", "BOSCHLTD", "BRITANNIA", "CGPOWER", "CANBK", "CHOLAFIN", "CUMMINSIND", "DLF", "DIVISLAB",
        "GAIL", "GODREJCP", "HDFCAMC", "HAL", "HINDZINC", "HYUNDAI", "INDHOTEL", "IOC", "IRFC",
        "JINDALSTEL", "LTM", "LODHA", "MAZDOCK", "MUTHOOTFIN", "PIDILITIND", "PFC", "PNB", "RECLTD",
        "MOTHERSON", "SHREECEM", "ENRIN", "SIEMENS", "SOLARINDS", "TVSMOTOR", "TATACAP", "TMCV",
        "TATAPOWER", "TORNTPHARM", "UNIONBANK", "UNITDSPR", "VBL", "VEDL", "ZYDUSLIFE",
    ],
    "NIFTYMIDCAP150": [
        "360ONE", "3MINDIA", "ACC", "AIAENG", "APLAPOLLO", "AUBANK", "AWL", "ABBOTINDIA", "ATGL",
        "ABCAPITAL", "AJANTPHARM", "ALKEM", "ANTHEM", "APARINDS", "APOLLOTYRE", "ASHOKLEY", "ASTRAL",
        "AUROPHARMA", "AIIL", "BSE", "BAJAJHFL", "BALKRISIND", "BANKINDIA", "MAHABANK", "BERGEPAINT",
        "BDL", "BHARATFORG", "BHEL", "BHARTIHEXA", "GROWW", "BIOCON", "BLUESTARCO", "CRISIL",
        "COCHINSHIP", "COFORGE", "COLPAL", "CONCOR", "COROMANDEL", "DABUR", "DALBHARAT", "DIXON",
        "ENDURANCE", "ESCORTS", "EXIDEIND", "NYKAA", "FEDERALBNK", "FORTIS", "GVT&D", "GMRAIRPORT",
        "GICRE", "GLAXO", "GLENMARK", "MEDANTA", "GODFRYPHLP", "GODREJIND", "GODREJPROP", "FLUOROCHEM",
        "HDBFS", "HAVELLS", "HEROMOTOCO", "HEXT", "HINDPETRO", "POWERINDIA", "HONAUT", "HUDCO",
        "ICICIGI", "ICICIAMC", "ICICIPRULI", "IDFCFIRSTB", "ITCHOTELS", "INDIANB", "IRCTC", "IREDA",
        "INDUSTOWER", "INDUSINDBK", "NAUKRI", "IPCALAB", "JKCEMENT", "JSWENERGY", "JSWINFRA", "JSL",
        "JUBLFOOD", "KPRMILL", "KEI", "KPITTECH", "KALYANKJIL", "LTF", "LTTS", "LGEINDIA", "LICHSGFIN",
        "LAURUSLABS", "LENSKART", "LICI", "LINDEINDIA", "LLOYDSME", "LUPIN", "MRF", "M&MFIN", "MANKIND",
        "MARICO", "MFSL", "MOTILALOFS", "MPHASIS", "MCX", "NHPC", "NLCINDIA", "NMDC", "NTPCGREEN",
        "NATIONALUM", "NAM-INDIA", "OBEROIRLTY", "OIL", "PAYTM", "OFSS", "POLICYBZR", "PIIND",
        "PAGEIND", "PATANJALI", "PERSISTENT", "PETRONET", "PHOENIXLTD", "POLYCAB", "PREMIERENE",
        "PRESTIGE", "RADICO", "RVNL", "SBICARD", "SJVN", "SRF", "SCHAEFFLER", "SAIL", "SUNDARMFIN",
        "SUPREMEIND", "SUZLON", "SWIGGY", "TATACOMM", "TATAELXSI", "TATAINVEST", "NIACL", "THERMAX",
        "TORNTPOWER", "TIINDIA", "UNOMINDA", "UPL", "UBL", "VMM", "IDEA", "VOLTAS", "WAAREEENER",
        "YESBANK",
    ],
    "NIFTYSMALLCAP250": [
        "ACMESOLAR", "AADHARHFC", "AARTIIND", "AAVAS", "ACE", "ACUTAAS", "ABFRL", "ABLBL", "ABREL",
        "ABSLAMC", "CPPLUS", "AEGISLOG", "AEGISVOPAK", "AFCONS", "AFFLE", "ABDL", "ARE&M", "AMBER",
        "ANANDRATHI", "ANANTRAJ", "ANGELONE", "ANURAS", "APTUS", "ASAHIINDIA", "ASTERDM", "ATHERENERG",
        "ATUL", "BEML", "BLS", "BALRAMCHIN", "BANDHANBNK", "BATAINDIA", "BAYERCROP", "BELRISE",
        "BIKAJI", "BSOFT", "BLUEDART", "BLUEJET", "BBTC", "FIRSTCRY", "BRIGADE", "MAPMYINDIA", "CCL",
        "CESC", "CIEINDIA", "CANFINHOME", "CANHLIFE", "CAPLIPOINT", "CGCL", "CARBORUNIV", "CARTRADE",
        "CASTROLIND", "CEATLTD", "CEMPRO", "CENTRALBK", "CDSL", "CHALET", "CHAMBLFERT", "CHENNPETRO",
        "CHOICEIN", "CHOLAHLDNG", "CUB", "CLEAN", "COHANCE", "CAMS", "CONCORDBIO", "CRAFTSMAN",
        "CREDITACC", "CROMPTON", "CYIENT", "DCMSHRIRAM", "DATAPATTNS", "DOMS", "DEEPAKFERT", "DEEPAKNTR", "DELHIVERY",
        "DEVYANI", "LALPATHLAB", "EIDPARRY", "EIHOTEL", "ELECON", "ELGIEQUIP", "EMAMILTD", "EMCURE",
        "EMMVEE", "ENGINERSIN", "ERIS", "FACT", "FINCABLES", "FSL", "FIVESTAR", "FORCEMOT", "GABRIEL",
        "GALLANTT", "GRSE", "GILLETTE", "GLAND", "GODIGIT", "GPIL", "GRANULES", "GRAPHITE", "GRAVITA",
        "GESHIP", "GMDCLTD", "HEG", "HBLENGINE", "HFCL", "HSCL", "HINDCOPPER", "HOMEFIRST", "HONASA",
        "IDBI", "IFCI", "IIFL", "IRB", "IRCON", "ITI", "INDGN", "INDIACEM", "INDIAMART", "IEX", "IOB",
        "IGL", "INOXWIND", "INTELLECT", "IGIL", "IKS", "JBCHEPHARM", "JBMA", "JKTYRE", "JMFINANCIL",
        "JSWCEMENT", "JSWDULUX", "JAINREC", "JPPOWER", "J&KBANK", "JINDALSAW", "JUBLINGREA",
        "JUBLPHARMA", "JWL", "JYOTICNC", "KAJARIACER", "KPIL", "KARURVYSYA", "KAYNES", "KEC",
        "KFINTECH", "KIRLOSENG", "KIMS", "LTFOODS", "LATENTVIEW", "THELEELA", "LEMONTREE", "MMTC",
        "MGL", "MANAPPURAM", "MRPL", "MEESHO", "MINDACORP", "MSUMI", "NATCOPHARM", "NBCC", "NCC",
        "NSLNISP", "NH", "NAVA", "NAVINFLUOR", "NETWEB", "NEULANDLAB", "NEWGEN", "NIVABUPA", "NUVAMA",
        "NUVOCO", "OLAELEC", "OLECTRA", "ONESOURCE", "PCBL", "PGEL", "PNBHOUSING", "PTCIL", "PVRINOX",
        "PARADEEP", "PFIZER", "PWL", "PINELABS", "PIRAMALFIN", "PPLPHARMA", "POLYMED", "POONAWALLA",
        "RRKABEL", "RBLBANK", "RHIM", "RITES", "RAILTEL", "RAINBOW", "RKFORGE", "REDINGTON", "RPOWER",
        "SBFC", "SAGILITY", "SAILIFE", "SAMMAANCAP", "SAPPHIRE", "SARDAEN", "SAREGAMA", "SCHNEIDER",
        "SCI", "SHYAMMETL", "SIGNATURE", "SOBHA", "SONACOMS", "SONATSOFTW", "STARHEALTH", "SUMICHEM",
        "SUNTV", "SPLPETRO", "SWANCORP", "SYNGENE", "SYRMA", "TBOTEK", "TATACHEM", "TATATECH", "TTML",
        "TECHNOE", "TEGA", "TEJASNET", "TENNIND", "RAMCOCEM", "TIMKEN", "TITAGARH", "TARIL",
        "TRAVELFOOD", "TRIDENT", "TRITURBINE", "UCOBANK", "UTIAMC", "URBANCO", "USHAMART", "VTL",
        "VIJAYA", "WELCORP", "WELSPUNLIV", "WHIRLPOOL", "WOCKPHARMA", "ZFCVINDIA", "ZEEL", "ZENTEC",
        "ZENSARTECH", "ZYDUSWELL", "ECLERX",
    ],
    "NIFTY100": [
        "ABB", "ADANIENSOL", "ADANIENT", "ADANIGREEN", "ADANIPORTS", "ADANIPOWER", "AMBUJACEM",
        "APOLLOHOSP", "ASIANPAINT", "DMART", "AXISBANK", "BAJAJ-AUTO", "BAJFINANCE", "BAJAJFINSV",
        "BAJAJHLDNG", "BANKBARODA", "BEL", "BPCL", "BHARTIARTL", "BOSCHLTD", "BRITANNIA", "CGPOWER",
        "CANBK", "CHOLAFIN", "CIPLA", "COALINDIA", "CUMMINSIND", "DLF", "DIVISLAB", "DRREDDY",
        "EICHERMOT", "ETERNAL", "GAIL", "GODREJCP", "GRASIM", "HCLTECH", "HDFCAMC", "HDFCBANK",
        "HDFCLIFE", "HINDALCO", "HAL", "HINDUNILVR", "HINDZINC", "HYUNDAI", "ICICIBANK", "ITC",
        "INDHOTEL", "IOC", "IRFC", "INFY", "INDIGO", "JSWSTEEL", "JINDALSTEL", "JIOFIN", "KOTAKBANK",
        "LTM", "LT", "LODHA", "M&M", "MARUTI", "MAXHEALTH", "MAZDOCK", "MUTHOOTFIN", "NTPC",
        "NESTLEIND", "ONGC", "PIDILITIND", "PFC", "POWERGRID", "PNB", "RECLTD", "RELIANCE", "SBILIFE",
        "MOTHERSON", "SHREECEM", "SHRIRAMFIN", "ENRIN", "SIEMENS", "SOLARINDS", "SBIN", "SUNPHARMA",
        "TVSMOTOR", "TATACAP", "TCS", "TATACONSUM", "TMCV", "TMPV", "TATAPOWER", "TATASTEEL", "TECHM",
        "TITAN", "TORNTPHARM", "TRENT", "ULTRACEMCO", "UNIONBANK", "UNITDSPR", "VBL", "VEDL", "WIPRO",
        "ZYDUSLIFE",
    ],
    "NIFTY500": [
        "360ONE", "3MINDIA", "ABB", "ACC", "ACMESOLAR", "AIAENG", "APLAPOLLO", "AUBANK", "AWL",
        "AADHARHFC", "AARTIIND", "AAVAS", "ABBOTINDIA", "ACE", "ACUTAAS", "ADANIENSOL", "ADANIENT",
        "ADANIGREEN", "ADANIPORTS", "ADANIPOWER", "ATGL", "ABCAPITAL", "ABFRL", "ABLBL", "ABREL",
        "ABSLAMC", "CPPLUS", "AEGISLOG", "AEGISVOPAK", "AFCONS", "AFFLE", "AJANTPHARM", "ALKEM",
        "ABDL", "ARE&M", "AMBER", "AMBUJACEM", "ANANDRATHI", "ANANTRAJ", "ANGELONE", "ANTHEM",
        "ANURAS", "APARINDS", "APOLLOHOSP", "APOLLOTYRE", "APTUS", "ASAHIINDIA", "ASHOKLEY",
        "ASIANPAINT", "ASTERDM", "ASTRAL", "ATHERENERG", "ATUL", "AUROPHARMA", "AIIL", "DMART",
        "AXISBANK", "BEML", "BLS", "BSE", "BAJAJ-AUTO", "BAJFINANCE", "BAJAJFINSV", "BAJAJHLDNG",
        "BAJAJHFL", "BALKRISIND", "BALRAMCHIN", "BANDHANBNK", "BANKBARODA", "BANKINDIA", "MAHABANK",
        "BATAINDIA", "BAYERCROP", "BELRISE", "BERGEPAINT", "BDL", "BEL", "BHARATFORG", "BHEL", "BPCL",
        "BHARTIARTL", "BHARTIHEXA", "BIKAJI", "GROWW", "BIOCON", "BSOFT", "BLUEDART", "BLUEJET",
        "BLUESTARCO", "BBTC", "BOSCHLTD", "FIRSTCRY", "BRIGADE", "BRITANNIA", "MAPMYINDIA", "CCL",
        "CESC", "CGPOWER", "CIEINDIA", "CRISIL", "CANFINHOME", "CANBK", "CANHLIFE", "CAPLIPOINT",
        "CGCL", "CARBORUNIV", "CARTRADE", "CASTROLIND", "CEATLTD", "CEMPRO", "CENTRALBK", "CDSL",
        "CHALET", "CHAMBLFERT", "CHENNPETRO", "CHOICEIN", "CHOLAHLDNG", "CHOLAFIN", "CIPLA", "CUB",
        "CLEAN", "COALINDIA", "COCHINSHIP", "COFORGE", "COHANCE", "COLPAL", "CAMS", "CONCORDBIO",
        "CONCOR", "COROMANDEL", "CRAFTSMAN", "CREDITACC", "CROMPTON", "CUMMINSIND", "CYIENT",
        "DCMSHRIRAM", "DLF", "DOMS", "DABUR", "DALBHARAT", "DATAPATTNS", "DEEPAKFERT", "DEEPAKNTR",
        "DELHIVERY", "DEVYANI", "LALPATHLAB", "DIVISLAB", "DIXON", "DRREDDY", "EIDPARRY", "EIHOTEL",
        "EICHERMOT", "ELECON", "ELGIEQUIP", "EMAMILTD", "EMCURE", "EMMVEE", "ENDURANCE", "ENGINERSIN",
        "ERIS", "ESCORTS", "ETERNAL", "EXIDEIND", "NYKAA", "FEDERALBNK", "FACT", "FINCABLES", "FSL",
        "FIVESTAR", "FORCEMOT", "FORTIS", "GAIL", "GVT&D", "GMRAIRPORT", "GABRIEL", "GALLANTT", "GRSE",
        "GICRE", "GILLETTE", "GLAND", "GLAXO", "GLENMARK", "MEDANTA", "GODIGIT", "GPIL", "GODFRYPHLP",
        "GODREJCP", "GODREJIND", "GODREJPROP", "GRANULES", "GRAPHITE", "GRASIM", "GRAVITA", "GESHIP",
        "FLUOROCHEM", "GMDCLTD", "HEG", "HBLENGINE", "HCLTECH", "HDBFS", "HDFCAMC", "HDFCBANK",
        "HDFCLIFE", "HFCL", "HAVELLS", "HEROMOTOCO", "HEXT", "HSCL", "HINDALCO", "HAL", "HINDCOPPER",
        "HINDPETRO", "HINDUNILVR", "HINDZINC", "POWERINDIA", "HOMEFIRST", "HONASA", "HONAUT", "HUDCO",
        "HYUNDAI", "ICICIBANK", "ICICIGI", "ICICIAMC", "ICICIPRULI", "IDBI", "IDFCFIRSTB", "IFCI",
        "IIFL", "IRB", "IRCON", "ITCHOTELS", "ITC", "ITI", "INDGN", "INDIACEM", "INDIAMART", "INDIANB",
        "IEX", "INDHOTEL", "IOC", "IOB", "IRCTC", "IRFC", "IREDA", "IGL", "INDUSTOWER", "INDUSINDBK",
        "NAUKRI", "INFY", "INOXWIND", "INTELLECT", "INDIGO", "IGIL", "IKS", "IPCALAB", "JBCHEPHARM",
        "JKCEMENT", "JBMA", "JKTYRE", "JMFINANCIL", "JSWCEMENT", "JSWDULUX", "JSWENERGY", "JSWINFRA",
        "JSWSTEEL", "JAINREC", "JPPOWER", "J&KBANK", "JINDALSAW", "JSL", "JINDALSTEL", "JIOFIN",
        "JUBLFOOD", "JUBLINGREA", "JUBLPHARMA", "JWL", "JYOTICNC", "KPRMILL", "KEI", "KPITTECH",
        "KAJARIACER", "KPIL", "KALYANKJIL", "KARURVYSYA", "KAYNES", "KEC", "KFINTECH", "KIRLOSENG",
        "KOTAKBANK", "KIMS", "LTF", "LTTS", "LGEINDIA", "LICHSGFIN", "LTFOODS", "LTM", "LT",
        "LATENTVIEW", "LAURUSLABS", "THELEELA", "LEMONTREE", "LENSKART", "LICI", "LINDEINDIA",
        "LLOYDSME", "LODHA", "LUPIN", "MMTC", "MRF", "MGL", "M&MFIN", "M&M", "MANAPPURAM", "MRPL",
        "MANKIND", "MARICO", "MARUTI", "MFSL", "MAXHEALTH", "MAZDOCK", "MEESHO", "MINDACORP", "MSUMI",
        "MOTILALOFS", "MPHASIS", "MCX", "MUTHOOTFIN", "NATCOPHARM", "NBCC", "NCC", "NHPC", "NLCINDIA",
        "NMDC", "NSLNISP", "NTPCGREEN", "NTPC", "NH", "NATIONALUM", "NAVA", "NAVINFLUOR", "NESTLEIND",
        "NETWEB", "NEULANDLAB", "NEWGEN", "NAM-INDIA", "NIVABUPA", "NUVAMA", "NUVOCO", "OBEROIRLTY",
        "ONGC", "OIL", "OLAELEC", "OLECTRA", "PAYTM", "ONESOURCE", "OFSS", "POLICYBZR", "PCBL", "PGEL",
        "PIIND", "PNBHOUSING", "PTCIL", "PVRINOX", "PAGEIND", "PARADEEP", "PATANJALI", "PERSISTENT",
        "PETRONET", "PFIZER", "PHOENIXLTD", "PWL", "PIDILITIND", "PINELABS", "PIRAMALFIN", "PPLPHARMA",
        "POLYMED", "POLYCAB", "POONAWALLA", "PFC", "POWERGRID", "PREMIERENE", "PRESTIGE", "PNB",
        "RRKABEL", "RBLBANK", "RECLTD", "RHIM", "RITES", "RADICO", "RVNL", "RAILTEL", "RAINBOW",
        "RKFORGE", "REDINGTON", "RELIANCE", "RPOWER", "SBFC", "SBICARD", "SBILIFE", "SJVN", "SRF",
        "SAGILITY", "SAILIFE", "SAMMAANCAP", "MOTHERSON", "SAPPHIRE", "SARDAEN", "SAREGAMA",
        "SCHAEFFLER", "SCHNEIDER", "SCI", "SHREECEM", "SHRIRAMFIN", "SHYAMMETL", "ENRIN", "SIEMENS",
        "SIGNATURE", "SOBHA", "SOLARINDS", "SONACOMS", "SONATSOFTW", "STARHEALTH", "SBIN", "SAIL",
        "SUMICHEM", "SUNPHARMA", "SUNTV", "SUNDARMFIN", "SUPREMEIND", "SPLPETRO", "SUZLON",
        "SWANCORP", "SWIGGY", "SYNGENE", "SYRMA", "TBOTEK", "TVSMOTOR", "TATACAP", "TATACHEM",
        "TATACOMM", "TCS", "TATACONSUM", "TATAELXSI", "TATAINVEST", "TMCV", "TMPV", "TATAPOWER",
        "TATASTEEL", "TATATECH", "TTML", "TECHM", "TECHNOE", "TEGA", "TEJASNET", "TENNIND", "NIACL",
        "RAMCOCEM", "THERMAX", "TIMKEN", "TITAGARH", "TITAN", "TORNTPHARM", "TORNTPOWER", "TARIL",
        "TRAVELFOOD", "TRENT", "TRIDENT", "TRITURBINE", "TIINDIA", "UCOBANK", "UNOMINDA", "UPL",
        "UTIAMC", "ULTRACEMCO", "UNIONBANK", "UBL", "UNITDSPR", "URBANCO", "USHAMART", "VTL", "VBL",
        "VEDL", "VIJAYA", "VMM", "IDEA", "VOLTAS", "WAAREEENER", "WELCORP", "WELSPUNLIV", "WHIRLPOOL",
        "WIPRO", "WOCKPHARMA", "YESBANK", "ZFCVINDIA", "ZEEL", "ZENTEC", "ZENSARTECH", "ZYDUSLIFE",
        "ZYDUSWELL", "ECLERX",
    ],
    "NIFTYBANK": [
        "AUBANK", "AXISBANK", "BANKBARODA", "CANBK", "FEDERALBNK", "HDFCBANK", "ICICIBANK",
        "IDFCFIRSTB", "INDUSINDBK", "KOTAKBANK", "PNB", "SBIN", "UNIONBANK", "YESBANK",
    ],
    "NIFTYFINSERVICE": [
        "HDFCBANK", "ICICIBANK", "SBIN", "BAJFINANCE", "AXISBANK", "KOTAKBANK", "BAJAJFINSV",
        "SHRIRAMFIN", "SBILIFE", "BSE", "JIOFIN", "CHOLAFIN", "PFC", "MUTHOOTFIN", "HDFCLIFE",
        "RECLTD", "ICICIGI", "SBICARD", "MFSL", "LICHSGFIN",
    ],
    "NIFTYPSUBANK": [
        "BANKBARODA", "BANKINDIA", "MAHABANK", "CANBK", "CENTRALBK", "INDIANB", "IOB", "PSB", "PNB",
        "SBIN", "UCOBANK", "UNIONBANK",
    ],
    "NIFTYPVTBANK": [
        "AXISBANK", "BANDHANBNK", "FEDERALBNK", "HDFCBANK", "ICICIBANK", "IDFCFIRSTB", "INDUSINDBK",
        "KOTAKBANK", "RBLBANK", "YESBANK",
    ],
    "NIFTYIT": [
        "COFORGE", "HCLTECH", "INFY", "LTM", "MPHASIS", "OFSS", "PERSISTENT", "TCS", "TECHM", "WIPRO",
    ],
    "NIFTYPHARMA": [
        "ABBOTINDIA", "AJANTPHARM", "ALKEM", "AUROPHARMA", "BIOCON", "CIPLA", "DIVISLAB", "DRREDDY",
        "GLAND", "GLENMARK", "IPCALAB", "JBCHEPHARM", "LAURUSLABS", "LUPIN", "MANKIND", "PPLPHARMA",
        "SUNPHARMA", "TORNTPHARM", "WOCKPHARMA", "ZYDUSLIFE",
    ],
    "NIFTYHEALTHCARE": [
        "ABBOTINDIA", "ALKEM", "APOLLOHOSP", "AUROPHARMA", "BIOCON", "CIPLA", "DIVISLAB", "DRREDDY",
        "FORTIS", "GLENMARK", "IPCALAB", "LAURUSLABS", "LUPIN", "MANKIND", "MAXHEALTH", "PPLPHARMA",
        "SUNPHARMA", "SYNGENE", "TORNTPHARM", "ZYDUSLIFE",
    ],
    "NIFTYFMCG": [
        "BRITANNIA", "COLPAL", "DABUR", "EMAMILTD", "GODREJCP", "HINDUNILVR", "ITC", "MARICO",
        "NESTLEIND", "PATANJALI", "RADICO", "TATACONSUM", "UBL", "UNITDSPR", "VBL",
    ],
    "NIFTYAUTO": [
        "ASHOKLEY", "BAJAJ-AUTO", "BHARATFORG", "BOSCHLTD", "EICHERMOT", "EXIDEIND", "HEROMOTOCO",
        "M&M", "MARUTI", "MOTHERSON", "SONACOMS", "TVSMOTOR", "TMPV", "TIINDIA", "UNOMINDA",
    ],
    "NIFTYREALTY": [
        "ABREL", "ANANTRAJ", "BRIGADE", "DLF", "GODREJPROP", "LODHA", "OBEROIRLTY", "PHOENIXLTD",
        "PRESTIGE", "SOBHA",
    ],
    "NIFTYMEDIA": [
        "DBCORP", "HATHWAY", "NAZARA", "NETWORK18", "PVRINOX", "PFOCUS", "SAREGAMA", "SUNTV",
        "TIPSMUSIC", "ZEEL",
    ],
    "NIFTYCONSDURABLE": [
        "AMBER", "BATAINDIA", "BLUESTARCO", "CROMPTON", "DIXON", "HAVELLS", "KAJARIACER",
        "KALYANKJIL", "LGEINDIA", "PGEL", "TITAN", "VOLTAS", "WHIRLPOOL",
    ],
    "NIFTYINFRA": [
        "ADANIGREEN", "ADANIPORTS", "AMBUJACEM", "APOLLOHOSP", "ASHOKLEY", "BHARATFORG", "BPCL",
        "BHARTIARTL", "CGPOWER", "CUMMINSIND", "DLF", "FORTIS", "GAIL", "GRASIM", "HINDPETRO",
        "INDHOTEL", "IOC", "INDUSTOWER", "INDIGO", "LT", "MAXHEALTH", "NTPC", "ONGC", "POWERGRID",
        "RELIANCE", "MOTHERSON", "SHREECEM", "SUZLON", "TATAPOWER", "ULTRACEMCO",
    ],
    "NIFTYCPSE": [
        "BEL", "COALINDIA", "COCHINSHIP", "NBCC", "NHPC", "NLCINDIA", "NTPC", "ONGC", "OIL",
        "POWERGRID", "SJVN",
    ],
    "NIFTYPSE": [
        "BEL", "BHEL", "BPCL", "COALINDIA", "CONCOR", "GAIL", "HAL", "HINDPETRO", "IOC", "IRCTC",
        "IRFC", "NHPC", "NMDC", "NTPC", "ONGC", "OIL", "PFC", "POWERGRID", "RECLTD", "RVNL",
    ],
    "NIFTY100ESG": [
        "RELIANCE", "HDFCBANK", "BHARTIARTL", "ICICIBANK", "SBIN", "TCS", "BAJFINANCE", "HINDUNILVR",
        "MARUTI", "INFY", "ADANIENT", "ADANIPORTS", "ADANIPOWER", "AXISBANK", "TITAN", "M&M",
        "ULTRACEMCO", "NTPC", "HCLTECH", "ONGC", "BAJAJFINSV", "JSWSTEEL", "BAJAJ-AUTO", "NESTLEIND",
        "ETERNAL", "DMART", "POWERGRID", "ASIANPAINT", "ADANIGREEN", "SHRIRAMFIN", "TATASTEEL",
        "HINDZINC", "GRASIM", "HINDALCO", "EICHERMOT", "ADANIENSOL", "IOC", "SBILIFE", "DIVISLAB",
        "WIPRO", "TVSMOTOR", "DLF", "TORNTPHARM", "PIDILITIND", "VBL", "HYUNDAI", "JIOFIN",
        "CUMMINSIND", "TRENT", "CHOLAFIN", "MOTHERSON", "ABB", "CGPOWER", "TECHM", "BPCL", "PFC",
        "BANKBARODA", "BRITANNIA", "APOLLOHOSP", "MUTHOOTFIN", "UNIONBANK", "ENRIN", "SIEMENS",
        "BOSCHLTD", "HDFCLIFE", "TATAPOWER", "LTM", "BAJAJHLDNG", "HDFCAMC", "IRFC", "CANBK", "GAIL",
        "GODREJCP", "TATACONSUM", "AMBUJACEM", "MAXHEALTH", "JINDALSTEL", "INDHOTEL", "SHREECEM",
        "RECLTD",
    ],
    "NIFTYCONSUMPTION": [
        "ADANIPOWER", "APOLLOHOSP", "ASIANPAINT", "DMART", "BAJAJ-AUTO", "BHARTIARTL", "BRITANNIA",
        "DLF", "DIXON", "EICHERMOT", "ETERNAL", "GODREJCP", "HAVELLS", "HEROMOTOCO", "HINDUNILVR",
        "ITC", "INDHOTEL", "NAUKRI", "INDIGO", "M&M", "MARUTI", "MAXHEALTH", "NESTLEIND", "TVSMOTOR",
        "TATACONSUM", "TATAPOWER", "TITAN", "TRENT", "UNITDSPR", "VBL",
    ],
    "NIFTYDIVOPP50": [
        "ANGELONE", "ASHOKLEY", "BAJAJ-AUTO", "BANKBARODA", "BANKINDIA", "MAHABANK", "BPCL",
        "BRITANNIA", "CANBK", "COALINDIA", "COLPAL", "CUMMINSIND", "GAIL", "GODREJCP", "HCLTECH",
        "HDFCAMC", "HEROMOTOCO", "HINDPETRO", "HINDUNILVR", "HINDZINC", "HUDCO", "ITC", "INDIANB",
        "IOC", "IRFC", "INFY", "M&MFIN", "MPHASIS", "NHPC", "NMDC", "NTPC", "NATIONALUM", "ONGC",
        "OIL", "OFSS", "PAGEIND", "PFC", "POWERGRID", "PNB", "RECLTD", "REDINGTON", "SHRIRAMFIN",
        "SBIN", "SAIL", "TCS", "TATASTEEL", "TECHM", "UNIONBANK", "VEDL", "WIPRO",
    ],
    "NIFTYLOWVOL": [
        "APOLLOHOSP", "ASIANPAINT", "DMART", "AXISBANK", "BAJAJ-AUTO", "BAJAJFINSV", "BHARTIARTL",
        "BRITANNIA", "CIPLA", "COLPAL", "DABUR", "DIVISLAB", "DRREDDY", "GODREJCP", "GRASIM",
        "HCLTECH", "HDFCBANK", "HDFCLIFE", "HEROMOTOCO", "HINDUNILVR", "ICICIBANK", "ICICIGI", "ITC",
        "IRCTC", "INFY", "JSWSTEEL", "KOTAKBANK", "LT", "LUPIN", "MRF", "MARICO", "MARUTI", "NTPC",
        "NESTLEIND", "PAGEIND", "PIDILITIND", "POWERGRID", "RELIANCE", "SBICARD", "SBILIFE", "SBIN",
        "SUNPHARMA", "TCS", "TATACONSUM", "TECHM", "TITAN", "TORNTPHARM", "ULTRACEMCO", "UNITDSPR",
        "WIPRO",
    ],
    "NIFTY200MOMENTUM30": [
        "ABB", "ADANIENSOL", "ADANIGREEN", "ADANIPOWER", "ABCAPITAL", "BSE", "BHARATFORG", "BHEL",
        "CGPOWER", "CUMMINSIND", "FEDERALBNK", "GVT&D", "GLENMARK", "HINDALCO", "POWERINDIA", "KEI",
        "LTF", "LAURUSLABS", "MCX", "NTPC", "NATIONALUM", "POLYCAB", "MOTHERSON", "SHRIRAMFIN",
        "SOLARINDS", "SAIL", "TATASTEEL", "TORNTPHARM", "VEDL", "IDEA",
    ],
    "NIFTY50VALUE20": [
        "RELIANCE", "HDFCBANK", "ICICIBANK", "SBIN", "TCS", "INFY", "AXISBANK", "KOTAKBANK", "ITC",
        "NTPC", "HCLTECH", "ONGC", "BAJAJFINSV", "COALINDIA", "POWERGRID", "TATASTEEL", "GRASIM",
        "HINDALCO", "WIPRO", "TMPV",
    ],
}
